PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "migrations" ("id" integer not null primary key autoincrement, "migration" varchar not null, "batch" integer not null);
INSERT INTO migrations VALUES(1,'2014_10_12_000000_create_users_table',1);
INSERT INTO migrations VALUES(2,'2019_12_14_000001_create_personal_access_tokens_table',1);
INSERT INTO migrations VALUES(3,'2022_05_10_1652181562_create_projects_table',1);
INSERT INTO migrations VALUES(4,'2022_05_10_1652181629_create_gig_orders_table',1);
INSERT INTO migrations VALUES(5,'2022_05_25_050841_create_project_durations_table',1);
INSERT INTO migrations VALUES(6,'2022_05_25_050841_create_seller_project_invites_table',1);
INSERT INTO migrations VALUES(7,'2022_05_25_121131_create_project_locations_table',1);
INSERT INTO migrations VALUES(8,'2022_06_06_110257_create_escrow_disburse_methods_table',1);
INSERT INTO migrations VALUES(9,'2022_06_30_114144_create_gig_order_activities_table',1);
INSERT INTO migrations VALUES(10,'2022_06_30_114144_create_project_activities_table',1);
INSERT INTO migrations VALUES(11,'2022_07_14_105543_create_disputes_table',1);
INSERT INTO migrations VALUES(12,'2022_07_19_084755_create_dispute_conversations_table',1);
INSERT INTO migrations VALUES(13,'2022_09_15_052911_create_project_categories_table',1);
INSERT INTO migrations VALUES(14,'2022_09_15_083959_create_gig_categories_table',1);
INSERT INTO migrations VALUES(15,'2022_09_15_084334_create_gig_category_features_table',1);
INSERT INTO migrations VALUES(16,'2022_09_15_084422_create_gigs_table',1);
INSERT INTO migrations VALUES(17,'2022_09_15_084458_create_gig_plans_table',1);
INSERT INTO migrations VALUES(18,'2022_09_15_084538_create_gig_addons_table',1);
INSERT INTO migrations VALUES(19,'2022_09_15_084601_create_gig_faqs_table',1);
INSERT INTO migrations VALUES(20,'2022_09_15_095953_create_gig_tags_table',1);
INSERT INTO migrations VALUES(21,'2022_09_15_102208_create_gig_category_link_table',1);
INSERT INTO migrations VALUES(22,'2024_01_01_000000_create_advertisers_table',1);
INSERT INTO migrations VALUES(23,'2024_01_01_000000_create_freelance_extensions',1);
INSERT INTO migrations VALUES(24,'2024_01_01_000000_create_headhunters_tables',1);
INSERT INTO migrations VALUES(25,'2024_01_01_000000_create_jobs_tables',1);
INSERT INTO migrations VALUES(26,'2024_01_01_000000_create_pro_network_tables',1);
INSERT INTO migrations VALUES(27,'2024_01_01_000000_create_webinars_table',1);
INSERT INTO migrations VALUES(28,'2024_01_01_000010_create_webinar_registrations_table',1);
INSERT INTO migrations VALUES(29,'2024_01_01_000020_create_recordings_table',1);
INSERT INTO migrations VALUES(30,'2024_01_01_000030_create_networking_sessions_table',1);
INSERT INTO migrations VALUES(31,'2024_01_01_000040_create_networking_participants_table',1);
INSERT INTO migrations VALUES(32,'2024_01_01_000050_create_podcast_series_table',1);
INSERT INTO migrations VALUES(33,'2024_01_01_000060_create_podcast_episodes_table',1);
INSERT INTO migrations VALUES(34,'2024_01_01_000070_create_interviews_table',1);
INSERT INTO migrations VALUES(35,'2024_01_01_000080_create_interview_slots_table',1);
INSERT INTO migrations VALUES(36,'2024_01_01_000090_create_interview_scores_table',1);
INSERT INTO migrations VALUES(37,'2024_01_01_000100_create_campaigns_table',1);
INSERT INTO migrations VALUES(38,'2024_01_01_000100_create_launchpad_tables',1);
INSERT INTO migrations VALUES(39,'2024_01_01_000100_create_tickets_table',1);
INSERT INTO migrations VALUES(40,'2024_01_01_000101_create_launchpad_task_progress_table',1);
INSERT INTO migrations VALUES(41,'2024_01_01_000110_create_networking_contact_exchanges_table',1);
INSERT INTO migrations VALUES(42,'2024_01_01_000110_create_podcast_series_followers_table',1);
INSERT INTO migrations VALUES(43,'2024_01_01_000115_add_podcast_episode_content_tables',1);
INSERT INTO migrations VALUES(44,'2024_01_01_000120_create_networking_pairings_table',1);
INSERT INTO migrations VALUES(45,'2024_01_01_000200_create_ad_groups_table',1);
INSERT INTO migrations VALUES(46,'2024_01_01_000200_create_ai_workspace_tables',1);
INSERT INTO migrations VALUES(47,'2024_01_01_000300_create_creatives_table',1);
INSERT INTO migrations VALUES(48,'2024_01_01_000300_create_volunteering_tables',1);
INSERT INTO migrations VALUES(49,'2024_01_01_000400_create_placements_table',1);
INSERT INTO migrations VALUES(50,'2024_01_01_000500_create_targeting_rules_table',1);
INSERT INTO migrations VALUES(51,'2024_01_01_000600_create_metrics_table',1);
INSERT INTO migrations VALUES(52,'2024_01_01_000700_create_forecasts_table',1);
INSERT INTO migrations VALUES(53,'2024_01_01_000800_create_keyword_prices_table',1);
INSERT INTO migrations VALUES(54,'2024_01_01_000900_create_affiliate_referrals_table',1);
INSERT INTO migrations VALUES(55,'2024_01_01_001000_create_affiliate_payouts_table',1);
INSERT INTO migrations VALUES(56,'2025_11_29_110000_create_notifications_table',1);
INSERT INTO migrations VALUES(57,'2025_11_29_120000_create_utilities_calendar_events_table',1);
INSERT INTO migrations VALUES(58,'2025_11_29_120100_add_metadata_to_notifications_table',1);
INSERT INTO migrations VALUES(59,'2025_11_30_013909_add_duration_flags_to_media_files_and_videos',1);
INSERT INTO migrations VALUES(60,'2025_11_30_120001_update_gigvora_verify_tables',1);
INSERT INTO migrations VALUES(61,'2025_11_30_150000_add_signals_to_keyword_prices_table',1);
INSERT INTO migrations VALUES(62,'2025_11_30_150000_enhance_feed_media_tables',1);
INSERT INTO migrations VALUES(63,'2025_11_30_150500_create_live_streaming_engagements_table',1);
INSERT INTO migrations VALUES(64,'2025_12_02_000000_create_audit_logs_table',1);
INSERT INTO migrations VALUES(65,'2025_12_05_000000_add_env_readiness_indexes',1);
CREATE TABLE IF NOT EXISTS "users" ("id" integer not null primary key autoincrement, "name" varchar not null, "email" varchar not null, "email_verified_at" datetime, "password" varchar not null, "user_role" varchar, "username" varchar, "remember_token" varchar, "created_at" datetime, "updated_at" datetime, "profile_locked_for_verification" tinyint(1) not null default '0', "profile_lock_reason" varchar);
INSERT INTO users VALUES(1,'Gigvora Admin','admin@gigvora.test','2025-12-03 05:20:06','$2y$10$JbKm.KwcTvp.I2uXeU.PDuT9zn8dI9QftPmaUf.CkqR1jjYYbRUBi','admin','gigvora-admin','YPlvzHz47a','2025-12-03 05:20:06','2025-12-03 05:20:06',0,NULL);
CREATE TABLE IF NOT EXISTS "personal_access_tokens" ("id" integer not null primary key autoincrement, "tokenable_type" varchar not null, "tokenable_id" integer not null, "name" varchar not null, "token" varchar not null, "abilities" text, "last_used_at" datetime, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "projects" ("id" integer not null primary key autoincrement, "author_id" integer, "project_category" integer, "project_title" varchar not null, "slug" varchar not null, "project_type" varchar check ("project_type" in ('hourly', 'fixed')), "project_payout_type" varchar check ("project_payout_type" in ('fixed', 'both', 'milestone', 'hourly')), "attachments" text, "project_description" text, "project_payment_mode" varchar, "project_max_hours" varchar, "project_min_price" float not null default '0', "project_max_price" float not null default '0', "project_country" varchar, "country_zipcode" varchar, "address" text, "project_duration" integer, "project_hiring_seller" integer, "project_expert_level" integer, "project_location" integer, "is_featured" integer not null default '0', "featured_expiry" datetime, "status" varchar check ("status" in ('draft', 'pending', 'publish', 'hired', 'completed', 'refunded', 'cancelled')) not null default 'draft', "deleted_at" datetime, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "gig_orders" ("id" integer not null primary key autoincrement, "author_id" integer, "gig_id" integer, "plan_type" varchar not null, "plan_amount" float not null default '0', "gig_features" text, "gig_addons" text, "downloadable" text, "gig_delivery_days" integer not null, "gig_start_time" datetime, "commission_type" integer not null default '0', "commission_amount" float not null default '0', "status" varchar check ("status" in ('draft', 'hired', 'queued', 'completed', 'disputed', 'refunded', 'rejected')) not null default 'draft', "deleted_at" datetime, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "project_durations" ("id" integer not null primary key autoincrement, "name" varchar not null, "status" varchar check ("status" in ('active', 'deactive')) not null default 'active', "deleted_at" datetime, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "seller_project_invites" ("id" integer not null primary key autoincrement, "seller_id" integer not null, "project_id" integer not null, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "project_locations" ("id" integer not null primary key autoincrement, "name" varchar not null, "status" varchar check ("status" in ('active', 'deactive')) not null default 'active', "deleted_at" datetime, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "escrow_disburse_methods" ("id" integer not null primary key autoincrement, "seller_id" integer not null, "project_id" integer not null, "disburse_methods_id" integer not null, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "gig_order_activities" ("id" integer not null primary key autoincrement, "sender_id" integer not null, "receiver_id" integer not null, "gig_id" integer not null, "order_id" integer not null, "type" varchar check ("type" in ('revision', 'final')) not null default 'revision', "attachments" text, "description" text not null, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "project_activities" ("id" integer not null primary key autoincrement, "sender_id" integer not null, "receiver_id" integer not null, "project_id" integer not null, "attachments" text, "description" text not null, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "disputes" ("id" integer not null primary key autoincrement, "created_by" integer, "created_to" integer, "proposal_id" integer, "gig_order_id" integer, "price" float not null default '0', "dispute_issue" varchar, "dispute_detail" text, "dispute_log" text, "resolved_by" varchar check ("resolved_by" in ('admin', 'seller')) not null default 'seller', "favour_to" varchar check ("favour_to" in ('seller', 'buyer')), "status" varchar check ("status" in ('publish', 'declined', 'refunded', 'resolved', 'disputed', 'processing', 'cancelled')) not null default 'publish', "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "dispute_conversations" ("id" integer not null primary key autoincrement, "sender_id" integer not null, "dispute_id" integer not null, "message_id" integer, "message" text, "attachments" text, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "project_categories" ("id" integer not null primary key autoincrement, "parent_id" integer, "name" varchar not null, "image" text, "slug" varchar not null, "description" text, "status" varchar check ("status" in ('active', 'deactive')) not null default 'active', "deleted_at" datetime, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "gig_categories" ("id" integer not null primary key autoincrement, "parent_id" integer, "name" varchar not null, "image" text, "slug" varchar not null, "description" text, "status" varchar check ("status" in ('active', 'deactive')) not null default 'active', "deleted_at" datetime, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "gig_category_features" ("id" integer not null primary key autoincrement, "category_id" integer, "label" varchar not null, "options" text, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "gigs" ("id" integer not null primary key autoincrement, "author_id" integer not null, "title" varchar not null, "slug" varchar not null, "country" varchar not null, "zipcode" varchar not null, "address" text, "description" text, "attachments" text, "downloadable" text, "is_featured" integer not null default '0', "featured_expiry" datetime, "status" varchar check ("status" in ('publish', 'draft')) not null default 'publish', "deleted_at" datetime, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "gig_plans" ("id" integer not null primary key autoincrement, "gig_id" integer, "title" varchar not null, "description" text, "price" float not null default '0', "delivery_time" integer not null, "is_featured" integer not null default '0', "options" text, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "gig_addons" ("id" integer not null primary key autoincrement, "gig_id" integer not null, "addon_id" integer not null, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "gig_faqs" ("id" integer not null primary key autoincrement, "gig_id" integer not null, "question" text not null, "answer" text not null, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "gig_tags" ("id" integer not null primary key autoincrement, "gig_id" integer not null, "tag_name" varchar not null, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "gig_category_link" ("id" integer not null primary key autoincrement, "gig_id" integer not null, "category_id" integer not null, "category_level" integer not null, "created_at" datetime, "updated_at" datetime, foreign key("gig_id") references "gigs"("id"), foreign key("category_id") references "gig_categories"("id"));
CREATE TABLE IF NOT EXISTS "advertisers" ("id" integer not null primary key autoincrement, "user_id" integer not null, "name" varchar not null, "billing_email" varchar not null, "daily_spend_limit" numeric, "lifetime_spend_limit" numeric, "wallet_balance" numeric not null default '0', "status" varchar not null default 'active', "affiliate_id" integer, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete cascade, foreign key("affiliate_id") references "users"("id") on delete set null);
CREATE TABLE IF NOT EXISTS "project_freelancers" ("id" integer not null primary key autoincrement, "project_id" integer not null, "freelancer" varchar not null, "role" varchar not null default 'contributor', "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "project_tasks" ("id" integer not null primary key autoincrement, "project_id" integer not null, "title" varchar not null, "assignee" varchar, "status" varchar not null default 'pending', "due_date" datetime, "hours_logged" numeric not null default '0', "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "project_milestones" ("id" integer not null primary key autoincrement, "project_id" integer not null, "title" varchar not null, "amount" numeric not null, "status" varchar not null default 'pending', "due_date" datetime, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "project_submissions" ("id" integer not null primary key autoincrement, "project_id" integer not null, "milestone_id" integer, "notes" text not null, "attachment_url" varchar, "status" varchar not null default 'submitted', "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "project_invitations" ("id" integer not null primary key autoincrement, "project_id" integer not null, "freelancer" varchar not null, "message" text, "status" varchar not null default 'pending', "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "project_time_logs" ("id" integer not null primary key autoincrement, "project_id" integer not null, "freelancer" varchar not null, "hours" numeric not null, "note" text, "logged_at" datetime not null, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "project_reviews" ("id" integer not null primary key autoincrement, "project_id" integer not null, "rating" numeric not null, "comment" text, "author" varchar not null, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "gig_timeline_items" ("id" integer not null primary key autoincrement, "gig_id" integer not null, "title" varchar not null, "description" text, "occurred_at" datetime not null, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "gig_packages" ("id" integer not null primary key autoincrement, "gig_id" integer not null, "name" varchar not null, "price" numeric not null, "delivery_time" integer not null, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "gig_requirements" ("id" integer not null primary key autoincrement, "gig_id" integer not null, "prompt" text not null, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "gig_change_requests" ("id" integer not null primary key autoincrement, "gig_id" integer not null, "requester" varchar not null, "notes" text not null, "status" varchar not null default 'pending', "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "gig_reviews" ("id" integer not null primary key autoincrement, "gig_id" integer not null, "rating" numeric not null, "comment" text, "author" varchar not null, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "profile_portfolios" ("id" integer not null primary key autoincrement, "user_id" integer not null, "title" varchar not null, "description" text, "link" varchar, "thumbnail_url" varchar, "featured" tinyint(1) not null default '0', "completed_at" datetime, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "profile_reviews" ("id" integer not null primary key autoincrement, "user_id" integer not null, "reviewer" varchar, "rating" numeric not null, "comment" text, "reference" varchar, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "profile_educations" ("id" integer not null primary key autoincrement, "user_id" integer not null, "institution" varchar not null, "degree" varchar, "field" varchar, "start_year" integer, "end_year" integer, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "profile_certifications" ("id" integer not null primary key autoincrement, "user_id" integer not null, "name" varchar not null, "issuer" varchar, "credential_url" varchar, "issued_at" datetime, "expires_at" datetime, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "custom_gigs" ("id" integer not null primary key autoincrement, "title" varchar not null, "buyer" varchar not null, "scope" text, "status" varchar not null default 'draft', "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "dispute_stages" ("id" integer not null primary key autoincrement, "dispute_id" integer not null, "stage" varchar not null, "notes" text, "decision" text, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "freelance_tags" ("id" integer not null primary key autoincrement, "name" varchar not null, "slug" varchar not null, "type" varchar not null default 'freelancer', "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "freelance_tag_assignments" ("id" integer not null primary key autoincrement, "tag_id" integer not null, "assignable_id" integer not null, "assignable_type" varchar not null, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "escrow_actions" ("id" integer not null primary key autoincrement, "escrow_id" integer not null, "type" varchar not null, "amount" numeric, "actor" varchar, "decision" varchar, "notes" text, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "headhunter_profiles" ("id" integer not null primary key autoincrement, "user_id" integer not null, "status" varchar not null default 'pending', "bio" text, "industries" text, "skills" text, "approved_at" datetime, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id"));
CREATE TABLE IF NOT EXISTS "headhunter_mandates" ("id" integer not null primary key autoincrement, "headhunter_profile_id" integer not null, "organisation_id" integer, "title" varchar not null, "location" varchar, "fee_model" varchar, "fee_amount" numeric, "status" varchar not null default 'open', "requirements" text, "created_at" datetime, "updated_at" datetime, foreign key("headhunter_profile_id") references "headhunter_profiles"("id"), foreign key("organisation_id") references "organizations"("id"));
CREATE TABLE IF NOT EXISTS "headhunter_candidates" ("id" integer not null primary key autoincrement, "headhunter_profile_id" integer not null, "user_id" integer, "name" varchar not null, "email" varchar, "phone" varchar, "skills" text, "experience" text, "created_at" datetime, "updated_at" datetime, foreign key("headhunter_profile_id") references "headhunter_profiles"("id"), foreign key("user_id") references "users"("id"));
CREATE TABLE IF NOT EXISTS "headhunter_pipeline_items" ("id" integer not null primary key autoincrement, "headhunter_mandate_id" integer not null, "headhunter_candidate_id" integer not null, "stage" varchar not null default 'sourced', "notes" text, "moved_at" datetime, "created_at" datetime, "updated_at" datetime, foreign key("headhunter_mandate_id") references "headhunter_mandates"("id"), foreign key("headhunter_candidate_id") references "headhunter_candidates"("id"));
CREATE TABLE IF NOT EXISTS "headhunter_interviews" ("id" integer not null primary key autoincrement, "headhunter_pipeline_item_id" integer not null, "scheduled_by" integer not null, "scheduled_at" datetime not null, "status" varchar not null default 'scheduled', "summary" text, "created_at" datetime, "updated_at" datetime, foreign key("headhunter_pipeline_item_id") references "headhunter_pipeline_items"("id"), foreign key("scheduled_by") references "users"("id"));
CREATE TABLE IF NOT EXISTS "company_profiles" ("id" integer not null primary key autoincrement, "user_id" integer not null, "name" varchar not null, "slug" varchar not null, "headline" varchar, "description" text, "website" varchar, "location" varchar, "logo_path" varchar, "cover_path" varchar, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "candidate_profiles" ("id" integer not null primary key autoincrement, "user_id" integer not null, "headline" varchar, "bio" text, "location" varchar, "skills" text, "experience_years" integer, "resume_path" varchar, "portfolio_url" varchar, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "jobs" ("id" integer not null primary key autoincrement, "company_id" integer not null, "title" varchar not null, "slug" varchar not null, "description" text not null, "location" varchar, "workplace_type" varchar, "employment_type" varchar, "salary_min" numeric, "salary_max" numeric, "currency" varchar, "status" varchar not null default 'draft', "published_at" datetime, "expires_at" datetime, "is_featured" tinyint(1) not null default '0', "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "jobs_categories" ("id" integer not null primary key autoincrement, "name" varchar not null, "slug" varchar not null, "created_at" datetime, "updated_at" datetime);
INSERT INTO jobs_categories VALUES(1,'Engineering','engineering',NULL,NULL);
INSERT INTO jobs_categories VALUES(2,'Design','design',NULL,NULL);
INSERT INTO jobs_categories VALUES(3,'Marketing','marketing',NULL,NULL);
INSERT INTO jobs_categories VALUES(4,'Sales','sales',NULL,NULL);
CREATE TABLE IF NOT EXISTS "job_bookmarks" ("id" integer not null primary key autoincrement, "job_id" integer not null, "user_id" integer not null, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "cover_letters" ("id" integer not null primary key autoincrement, "candidate_id" integer not null, "title" varchar not null, "body" text not null, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "cv_templates" ("id" integer not null primary key autoincrement, "candidate_id" integer not null, "title" varchar not null, "content" text not null, "is_default" tinyint(1) not null default '0', "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "job_applications" ("id" integer not null primary key autoincrement, "job_id" integer not null, "candidate_id" integer not null, "cover_letter_id" integer, "cv_template_id" integer, "screening_score" integer, "status" varchar not null default 'applied', "notes" text, "resume_path" varchar, "applied_at" datetime, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "ats_pipelines" ("id" integer not null primary key autoincrement, "company_id" integer not null, "name" varchar not null, "is_default" tinyint(1) not null default '0', "created_at" datetime, "updated_at" datetime);
INSERT INTO ats_pipelines VALUES(1,0,'Default',1,'2025-12-03 05:20:06','2025-12-03 05:20:06');
CREATE TABLE IF NOT EXISTS "ats_stages" ("id" integer not null primary key autoincrement, "ats_pipeline_id" integer not null, "name" varchar not null, "position" integer not null default '0', "color" varchar, "created_at" datetime, "updated_at" datetime);
INSERT INTO ats_stages VALUES(1,1,'Applied',1,'#2f855a','2025-12-03 05:20:06','2025-12-03 05:20:06');
INSERT INTO ats_stages VALUES(2,1,'Phone Screen',2,'#3182ce','2025-12-03 05:20:06','2025-12-03 05:20:06');
INSERT INTO ats_stages VALUES(3,1,'Interview',3,'#805ad5','2025-12-03 05:20:06','2025-12-03 05:20:06');
INSERT INTO ats_stages VALUES(4,1,'Offer',4,'#dd6b20','2025-12-03 05:20:06','2025-12-03 05:20:06');
INSERT INTO ats_stages VALUES(5,1,'Hired',5,'#38a169','2025-12-03 05:20:06','2025-12-03 05:20:06');
CREATE TABLE IF NOT EXISTS "ats_stage_assignments" ("id" integer not null primary key autoincrement, "job_application_id" integer not null, "ats_stage_id" integer not null, "moved_by" integer, "notes" text, "moved_at" datetime, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "screening_questions" ("id" integer not null primary key autoincrement, "job_id" integer not null, "question" varchar not null, "type" varchar not null default 'text', "options" text, "is_required" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "screening_answers" ("id" integer not null primary key autoincrement, "job_application_id" integer not null, "screening_question_id" integer not null, "answer" text not null, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "subscriptions" ("id" integer not null primary key autoincrement, "company_id" integer not null, "plan" varchar not null, "job_credits" integer not null default '0', "renews_at" datetime, "status" varchar not null default 'active', "payment_reference" varchar, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "interview_schedules" ("id" integer not null primary key autoincrement, "job_application_id" integer not null, "scheduled_at" datetime not null, "location" varchar, "instructions" text, "meeting_link" varchar, "status" varchar not null default 'pending', "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "pro_network_connection_caches" ("id" integer not null primary key autoincrement, "user_id" integer not null, "connection_id" integer not null, "degree" integer not null, "connection_path" text, "mutual_count" integer not null default '0', "strength" integer not null default '0', "calculated_at" datetime, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete cascade, foreign key("connection_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "pro_network_mutual_connections" ("id" integer not null primary key autoincrement, "user_id" integer not null, "target_user_id" integer not null, "mutual_user_ids" text not null, "mutual_count" integer not null, "calculated_at" datetime, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete cascade, foreign key("target_user_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "pro_network_network_metrics" ("id" integer not null primary key autoincrement, "user_id" integer not null, "first_degree_count" integer not null default '0', "second_degree_count" integer not null default '0', "third_degree_count" integer not null default '0', "mutual_count" integer not null default '0', "suggestions" text, "calculated_at" datetime, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "pro_network_professional_profiles" ("id" integer not null primary key autoincrement, "user_id" integer not null, "headline" varchar, "tagline" varchar, "location" varchar, "top_skills" text, "available_for_work" tinyint(1) not null default '0', "public_url" varchar, "share_hash" varchar, "connections_count" integer not null default '0', "activity_summary" text, "interests" text, "visibility" varchar not null default 'public', "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "pro_network_profile_skills" ("id" integer not null primary key autoincrement, "user_id" integer not null, "name" varchar not null, "proficiency" varchar, "is_top_five" tinyint(1) not null default '0', "weight" integer not null default '0', "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "pro_network_profile_certifications" ("id" integer not null primary key autoincrement, "user_id" integer not null, "name" varchar not null, "authority" varchar, "license_number" varchar, "verification_url" varchar, "issued_at" date, "expires_at" date, "description" text, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "pro_network_profile_work_histories" ("id" integer not null primary key autoincrement, "user_id" integer not null, "title" varchar not null, "company_name" varchar not null, "employment_type" varchar, "location" varchar, "started_at" date, "ended_at" date, "is_current" tinyint(1) not null default '0', "description" text, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "pro_network_profile_education_histories" ("id" integer not null primary key autoincrement, "user_id" integer not null, "institution" varchar not null, "degree" varchar, "field" varchar, "started_at" date, "ended_at" date, "description" text, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "pro_network_profile_references" ("id" integer not null primary key autoincrement, "user_id" integer not null, "reference_user_id" integer, "name" varchar not null, "relationship" varchar, "contact_email" varchar, "contact_phone" varchar, "statement" text, "verified_at" datetime, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete cascade, foreign key("reference_user_id") references "users"("id") on delete set null);
CREATE TABLE IF NOT EXISTS "pro_network_profile_background_checks" ("id" integer not null primary key autoincrement, "user_id" integer not null, "status" varchar not null default 'pending', "provider" varchar, "reference" varchar, "checked_at" datetime, "expires_at" datetime, "notes" text, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "pro_network_profile_interests" ("id" integer not null primary key autoincrement, "user_id" integer not null, "interest" varchar not null, "weight" integer not null default '0', "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "pro_network_profile_opportunities" ("id" integer not null primary key autoincrement, "user_id" integer not null, "type" varchar not null, "title" varchar not null, "description" text, "rate" numeric, "currency" varchar, "status" varchar not null default 'open', "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "pro_network_company_profiles" ("id" integer not null primary key autoincrement, "page_id" integer not null, "headline" varchar, "industry" varchar, "location" varchar, "website" varchar, "metadata" text, "employee_count" integer not null default '0', "created_at" datetime, "updated_at" datetime, foreign key("page_id") references "pages"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "pro_network_company_employees" ("id" integer not null primary key autoincrement, "company_profile_id" integer not null, "user_id" integer not null, "role_title" varchar, "started_at" date, "ended_at" date, "is_current" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime, foreign key("company_profile_id") references "pro_network_company_profiles"("id") on delete cascade, foreign key("user_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "pro_network_marketplace_escrows" ("id" integer not null primary key autoincrement, "order_id" integer not null, "status" varchar not null default 'pending', "amount" numeric not null, "currency" varchar not null default 'USD', "delivery_method" varchar not null default 'delivery', "delivery_notes" varchar, "escrow_reference" varchar, "held_at" datetime, "released_at" datetime, "refunded_at" datetime, "created_at" datetime, "updated_at" datetime, foreign key("order_id") references "marketplace_orders"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "pro_network_marketplace_milestones" ("id" integer not null primary key autoincrement, "escrow_id" integer not null, "title" varchar not null, "amount" numeric not null, "status" varchar not null default 'pending', "due_at" datetime, "released_at" datetime, "refunded_at" datetime, "created_at" datetime, "updated_at" datetime, foreign key("escrow_id") references "pro_network_marketplace_escrows"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "pro_network_marketplace_transactions" ("id" integer not null primary key autoincrement, "escrow_id" integer not null, "user_id" integer, "type" varchar not null, "amount" numeric not null, "currency" varchar not null default 'USD', "notes" text, "created_at" datetime, "updated_at" datetime, foreign key("escrow_id") references "pro_network_marketplace_escrows"("id") on delete cascade, foreign key("user_id") references "users"("id") on delete set null);
CREATE TABLE IF NOT EXISTS "pro_network_marketplace_disputes" ("id" integer not null primary key autoincrement, "escrow_id" integer not null, "raised_by" integer not null, "reason" text not null, "status" varchar not null default 'open', "resolution_notes" text, "resolved_by" integer, "resolved_at" datetime, "created_at" datetime, "updated_at" datetime, foreign key("escrow_id") references "pro_network_marketplace_escrows"("id") on delete cascade, foreign key("raised_by") references "users"("id") on delete cascade, foreign key("resolved_by") references "users"("id") on delete set null);
CREATE TABLE IF NOT EXISTS "pro_network_marketplace_dispute_messages" ("id" integer not null primary key autoincrement, "dispute_id" integer not null, "user_id" integer not null, "message" text not null, "attachments" text, "created_at" datetime, "updated_at" datetime, foreign key("dispute_id") references "pro_network_marketplace_disputes"("id") on delete cascade, foreign key("user_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "pro_network_live_sessions" ("id" integer not null primary key autoincrement, "host_id" integer not null, "title" varchar not null, "description" text, "status" varchar not null default 'scheduled', "guest_user_ids" text, "likes_count" integer not null default '0', "donations_total" numeric not null default '0', "chat_channel" varchar, "started_at" datetime, "ended_at" datetime, "recording_path" varchar, "created_at" datetime, "updated_at" datetime, foreign key("host_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "pro_network_live_session_participants" ("id" integer not null primary key autoincrement, "live_session_id" integer not null, "user_id" integer not null, "role" varchar not null default 'guest', "joined_at" datetime, "left_at" datetime, "created_at" datetime, "updated_at" datetime, foreign key("live_session_id") references "pro_network_live_sessions"("id") on delete cascade, foreign key("user_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "pro_network_reactions" ("id" integer not null primary key autoincrement, "reactable_type" varchar not null, "reactable_id" integer not null, "user_id" integer not null, "type" varchar not null, "weight" integer not null default '1', "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "pro_network_reaction_aggregates" ("id" integer not null primary key autoincrement, "reactable_type" varchar not null, "reactable_id" integer not null, "counts" text, "dislikes" integer not null default '0', "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "pro_network_profile_reaction_scores" ("id" integer not null primary key autoincrement, "user_id" integer not null, "like_score" integer not null default '0', "dislike_count" integer not null default '0', "reaction_breakdown" text, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "pro_network_hashtags" ("id" integer not null primary key autoincrement, "tag" varchar not null, "normalized" varchar not null, "usage_count" integer not null default '0', "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "pro_network_hashtaggables" ("id" integer not null primary key autoincrement, "hashtag_id" integer not null, "hashtaggable_type" varchar not null, "hashtaggable_id" integer not null, "created_at" datetime, "updated_at" datetime, foreign key("hashtag_id") references "pro_network_hashtags"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "pro_network_music_tracks" ("id" integer not null primary key autoincrement, "title" varchar not null, "artist" varchar, "duration_seconds" integer not null default '0', "license" varchar, "storage_disk" varchar, "storage_path" varchar, "genre" varchar, "mood" varchar, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "pro_network_story_metadata" ("id" integer not null primary key autoincrement, "story_id" integer not null, "overlays" text, "filters" text, "stickers" text, "links" text, "music_track_id" integer, "live_session_id" integer, "created_at" datetime, "updated_at" datetime, foreign key("story_id") references "stories"("id") on delete cascade, foreign key("music_track_id") references "pro_network_music_tracks"("id") on delete set null, foreign key("live_session_id") references "pro_network_live_sessions"("id") on delete set null);
CREATE TABLE IF NOT EXISTS "pro_network_security_events" ("id" integer not null primary key autoincrement, "user_id" integer, "type" varchar not null, "ip" varchar, "user_agent" varchar, "severity" varchar not null default 'info', "context" text, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete set null);
CREATE TABLE IF NOT EXISTS "pro_network_moderation_queue" ("id" integer not null primary key autoincrement, "moderatable_type" varchar not null, "moderatable_id" integer not null, "reason" varchar not null, "status" varchar not null default 'pending', "flags" text, "actioned_by" integer, "resolved_at" datetime, "notes" text, "created_at" datetime, "updated_at" datetime, foreign key("actioned_by") references "users"("id") on delete set null);
CREATE TABLE IF NOT EXISTS "pro_network_bad_words" ("id" integer not null primary key autoincrement, "phrase" varchar not null, "severity" varchar not null default 'medium', "replacement" varchar, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "pro_network_bad_word_rules" ("id" integer not null primary key autoincrement, "name" varchar not null, "action" varchar not null, "applies_to" text, "active" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "pro_network_file_scans" ("id" integer not null primary key autoincrement, "path" varchar not null, "file_hash" varchar, "scanner_name" varchar, "status" varchar not null default 'pending', "details" text, "scanned_at" datetime, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "pro_network_analytics_events" ("id" integer not null primary key autoincrement, "event" varchar not null, "user_id" integer, "properties" text, "ip" varchar, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete set null);
CREATE TABLE IF NOT EXISTS "pro_network_analytics_metrics" ("id" integer not null primary key autoincrement, "entity_type" varchar not null, "entity_id" integer not null, "metric" varchar not null, "value" integer not null default '0', "meta" text, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "pro_network_account_types" ("id" integer not null primary key autoincrement, "slug" varchar not null, "name" varchar not null, "description" text, "features" text, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "pro_network_user_account_types" ("id" integer not null primary key autoincrement, "user_id" integer not null, "account_type_id" integer not null, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete cascade, foreign key("account_type_id") references "pro_network_account_types"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "pro_network_user_feature_flags" ("id" integer not null primary key autoincrement, "user_id" integer not null, "feature" varchar not null, "enabled" tinyint(1) not null default '0', "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "pro_network_age_verifications" ("id" integer not null primary key autoincrement, "user_id" integer not null, "status" varchar not null default 'pending', "provider" varchar, "provider_reference" varchar, "verified_at" datetime, "rejected_at" datetime, "payload" text, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "pro_network_age_verification_logs" ("id" integer not null primary key autoincrement, "age_verification_id" integer not null, "event" varchar not null, "meta" text, "created_at" datetime, "updated_at" datetime, foreign key("age_verification_id") references "pro_network_age_verifications"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "pro_network_newsletter_subscriptions" ("id" integer not null primary key autoincrement, "user_id" integer, "email" varchar not null, "subscribed" tinyint(1) not null default '1', "source" varchar, "locale" varchar, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete set null);
CREATE TABLE IF NOT EXISTS "pro_network_invite_contributions" ("id" integer not null primary key autoincrement, "inviter_id" integer not null, "invitee_id" integer, "post_id" integer, "role" varchar, "status" varchar not null default 'pending', "message" text, "created_at" datetime, "updated_at" datetime, foreign key("inviter_id") references "users"("id") on delete cascade, foreign key("invitee_id") references "users"("id") on delete set null, foreign key("post_id") references "posts"("id") on delete set null);
CREATE TABLE IF NOT EXISTS "pro_network_post_enhancements" ("id" integer not null primary key autoincrement, "post_id" integer not null, "type" varchar not null, "payload" text, "created_at" datetime, "updated_at" datetime, foreign key("post_id") references "posts"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "webinars" ("id" integer not null primary key autoincrement, "host_id" integer not null, "title" varchar not null, "description" text, "starts_at" datetime not null, "ends_at" datetime not null, "is_live" tinyint(1) not null default '0', "is_paid" tinyint(1) not null default '0', "price" numeric, "waiting_room_message" varchar, "stream_provider" varchar, "rtmp_endpoint" varchar, "recording_path" varchar, "status" varchar not null default 'scheduled', "metadata" text, "created_at" datetime, "updated_at" datetime, foreign key("host_id") references "users"("id"));
INSERT INTO webinars VALUES(1,1,'Sample Webinar 1','Generated seed webinar for onboarding flows.','2025-12-04 05:20:06','2025-12-04 06:20:06',0,0,0,NULL,NULL,NULL,NULL,'scheduled',NULL,'2025-12-03 05:20:06','2025-12-03 05:20:06');
INSERT INTO webinars VALUES(2,1,'Sample Webinar 2','Generated seed webinar for onboarding flows.','2025-12-05 05:20:06','2025-12-05 06:20:06',0,0,0,NULL,NULL,NULL,NULL,'scheduled',NULL,'2025-12-03 05:20:06','2025-12-03 05:20:06');
INSERT INTO webinars VALUES(3,1,'Sample Webinar 3','Generated seed webinar for onboarding flows.','2025-12-06 05:20:06','2025-12-06 06:20:06',0,0,0,NULL,NULL,NULL,NULL,'scheduled',NULL,'2025-12-03 05:20:06','2025-12-03 05:20:06');
CREATE TABLE IF NOT EXISTS "webinar_registrations" ("id" integer not null primary key autoincrement, "webinar_id" integer not null, "user_id" integer not null, "ticket_id" integer, "status" varchar not null default 'registered', "checked_in_at" datetime, "created_at" datetime, "updated_at" datetime, foreign key("webinar_id") references "webinars"("id"), foreign key("user_id") references "users"("id"), foreign key("ticket_id") references "tickets"("id"));
CREATE TABLE IF NOT EXISTS "recordings" ("id" integer not null primary key autoincrement, "recordable_type" varchar not null, "recordable_id" integer not null, "user_id" integer, "path" varchar not null, "duration" integer, "metadata" text, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id"));
CREATE TABLE IF NOT EXISTS "networking_sessions" ("id" integer not null primary key autoincrement, "host_id" integer not null, "title" varchar not null, "description" text, "duration_seconds" integer not null, "rotation_interval" integer not null, "starts_at" datetime not null, "is_paid" tinyint(1) not null default '0', "price" numeric, "status" varchar not null default 'scheduled', "metadata" text, "created_at" datetime, "updated_at" datetime, foreign key("host_id") references "users"("id"));
INSERT INTO networking_sessions VALUES(1,1,'Speed Networking 1','Autogenerated networking session.',1800,180,'2025-12-05 05:20:06',0,NULL,'scheduled',NULL,'2025-12-03 05:20:06','2025-12-03 05:20:06');
INSERT INTO networking_sessions VALUES(2,1,'Speed Networking 2','Autogenerated networking session.',1800,180,'2025-12-06 05:20:06',0,NULL,'scheduled',NULL,'2025-12-03 05:20:06','2025-12-03 05:20:06');
CREATE TABLE IF NOT EXISTS "networking_participants" ("id" integer not null primary key autoincrement, "networking_session_id" integer not null, "user_id" integer not null, "current_partner_id" integer, "rotation_position" integer not null default '1', "joined_at" datetime, "status" varchar not null default 'registered', "created_at" datetime, "updated_at" datetime, foreign key("networking_session_id") references "networking_sessions"("id"), foreign key("user_id") references "users"("id"), foreign key("current_partner_id") references "users"("id"));
CREATE TABLE IF NOT EXISTS "podcast_series" ("id" integer not null primary key autoincrement, "host_id" integer not null, "title" varchar not null, "description" text, "cover_art_path" varchar, "is_public" tinyint(1) not null default '0', "metadata" text, "created_at" datetime, "updated_at" datetime, foreign key("host_id") references "users"("id"));
INSERT INTO podcast_series VALUES(1,1,'Podcast Series 1','Seeded professional insights series.',NULL,1,NULL,'2025-12-03 05:20:06','2025-12-03 05:20:06');
INSERT INTO podcast_series VALUES(2,1,'Podcast Series 2','Seeded professional insights series.',NULL,1,NULL,'2025-12-03 05:20:06','2025-12-03 05:20:06');
CREATE TABLE IF NOT EXISTS "podcast_episodes" ("id" integer not null primary key autoincrement, "podcast_series_id" integer not null, "title" varchar not null, "description" text, "scheduled_for" datetime, "published_at" datetime, "audio_path" varchar, "duration" integer, "is_public" tinyint(1) not null default '0', "metadata" text, "created_at" datetime, "updated_at" datetime, "is_paid" tinyint(1) not null default '0', "entitlement_type" varchar, "price_cents" integer, "donation_suggested_cents" integer, foreign key("podcast_series_id") references "podcast_series"("id"));
CREATE TABLE IF NOT EXISTS "interviews" ("id" integer not null primary key autoincrement, "host_id" integer not null, "title" varchar not null, "description" text, "scheduled_at" datetime not null, "duration_minutes" integer not null, "is_panel" tinyint(1) not null default '0', "location" varchar, "metadata" text, "created_at" datetime, "updated_at" datetime, foreign key("host_id") references "users"("id"));
INSERT INTO interviews VALUES(1,1,'Interview Round 1','Seeded interview schedule.','2025-12-09 05:20:06',60,1,NULL,NULL,'2025-12-03 05:20:06','2025-12-03 05:20:06');
INSERT INTO interviews VALUES(2,1,'Interview Round 2','Seeded interview schedule.','2025-12-10 05:20:06',60,1,NULL,NULL,'2025-12-03 05:20:06','2025-12-03 05:20:06');
CREATE TABLE IF NOT EXISTS "interview_slots" ("id" integer not null primary key autoincrement, "interview_id" integer not null, "interviewer_id" integer not null, "interviewee_id" integer not null, "starts_at" datetime not null, "ends_at" datetime not null, "status" varchar not null default 'scheduled', "meeting_link" varchar, "metadata" text, "created_at" datetime, "updated_at" datetime, foreign key("interview_id") references "interviews"("id"), foreign key("interviewer_id") references "users"("id"), foreign key("interviewee_id") references "users"("id"));
CREATE TABLE IF NOT EXISTS "interview_scores" ("id" integer not null primary key autoincrement, "interview_id" integer not null, "interview_slot_id" integer not null, "interviewer_id" integer not null, "criteria" text not null, "scores" text not null, "comments" text, "created_at" datetime, "updated_at" datetime, foreign key("interview_id") references "interviews"("id"), foreign key("interview_slot_id") references "interview_slots"("id"), foreign key("interviewer_id") references "users"("id"));
CREATE TABLE IF NOT EXISTS "campaigns" ("id" integer not null primary key autoincrement, "advertiser_id" integer not null, "title" varchar not null, "start_date" datetime not null, "end_date" datetime not null, "budget" numeric not null, "bidding" varchar check ("bidding" in ('click', 'view', 'conversion')) not null, "status" varchar not null default 'draft', "spend" numeric not null default '0', "placement" varchar not null, "objective" varchar, "targeting_reach" integer not null default '0', "approval_state" varchar not null default 'pending', "created_at" datetime, "updated_at" datetime, foreign key("advertiser_id") references "advertisers"("id"));
CREATE TABLE IF NOT EXISTS "launchpad_programmes" ("id" integer not null primary key autoincrement, "creator_id" integer not null, "title" varchar not null, "category" varchar not null, "description" text, "estimated_hours" integer not null default '0', "estimated_weeks" integer not null default '0', "reference_offered" tinyint(1) not null default '0', "qualification_offered" tinyint(1) not null default '0', "pay_reduction_percentage" numeric, "status" varchar not null default 'draft', "created_at" datetime, "updated_at" datetime, foreign key("creator_id") references "users"("id"));
CREATE TABLE IF NOT EXISTS "launchpad_tasks" ("id" integer not null primary key autoincrement, "launchpad_programme_id" integer not null, "title" varchar not null, "description" text, "order" integer not null default '0', "estimated_hours" integer not null default '0', "created_at" datetime, "updated_at" datetime, foreign key("launchpad_programme_id") references "launchpad_programmes"("id"));
CREATE TABLE IF NOT EXISTS "launchpad_applications" ("id" integer not null primary key autoincrement, "launchpad_programme_id" integer not null, "user_id" integer not null, "status" varchar not null default 'submitted', "motivation" text, "reference_issued" tinyint(1) not null default '0', "qualification_issued" tinyint(1) not null default '0', "hours_gained" integer not null default '0', "weeks_gained" integer not null default '0', "created_at" datetime, "updated_at" datetime, foreign key("launchpad_programme_id") references "launchpad_programmes"("id"), foreign key("user_id") references "users"("id"));
CREATE TABLE IF NOT EXISTS "launchpad_interviews" ("id" integer not null primary key autoincrement, "launchpad_application_id" integer not null, "scheduled_by" integer not null, "scheduled_at" datetime not null, "status" varchar not null default 'scheduled', "notes" text, "created_at" datetime, "updated_at" datetime, foreign key("launchpad_application_id") references "launchpad_applications"("id"), foreign key("scheduled_by") references "users"("id"));
CREATE TABLE IF NOT EXISTS "tickets" ("id" integer not null primary key autoincrement, "ticketable_type" varchar not null, "ticketable_id" integer not null, "user_id" integer, "price" numeric not null default '0', "currency" varchar not null default 'USD', "status" varchar not null default 'available', "metadata" text, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id"));
CREATE TABLE IF NOT EXISTS "launchpad_application_task_progress" ("id" integer not null primary key autoincrement, "launchpad_application_id" integer not null, "launchpad_task_id" integer not null, "completed_at" datetime, "created_at" datetime, "updated_at" datetime, foreign key("launchpad_application_id") references "launchpad_applications"("id"), foreign key("launchpad_task_id") references "launchpad_tasks"("id"));
CREATE TABLE IF NOT EXISTS "networking_contact_exchanges" ("id" integer not null primary key autoincrement, "networking_session_id" integer not null, "user_id" integer not null, "partner_id" integer not null, "starred" tinyint(1) not null default '0', "follow_up_at" datetime, "notes" text, "metadata" text, "created_at" datetime, "updated_at" datetime, foreign key("networking_session_id") references "networking_sessions"("id"), foreign key("user_id") references "users"("id"), foreign key("partner_id") references "users"("id"));
CREATE TABLE IF NOT EXISTS "podcast_series_followers" ("id" integer not null primary key autoincrement, "podcast_series_id" integer not null, "user_id" integer not null, "created_at" datetime, "updated_at" datetime, foreign key("podcast_series_id") references "podcast_series"("id") on delete cascade, foreign key("user_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "podcast_episode_transcripts" ("id" integer not null primary key autoincrement, "podcast_episode_id" integer not null, "language" varchar not null default 'en', "source" varchar, "content" text not null, "metadata" text, "created_at" datetime, "updated_at" datetime, foreign key("podcast_episode_id") references "podcast_episodes"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "podcast_episode_highlights" ("id" integer not null primary key autoincrement, "podcast_episode_id" integer not null, "title" varchar not null, "description" text, "starts_at_seconds" integer not null, "ends_at_seconds" integer, "metadata" text, "created_at" datetime, "updated_at" datetime, foreign key("podcast_episode_id") references "podcast_episodes"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "podcast_episode_entitlements" ("id" integer not null primary key autoincrement, "podcast_episode_id" integer not null, "user_id" integer not null, "entitlement_type" varchar not null, "source" varchar, "granted_at" datetime default CURRENT_TIMESTAMP not null, "expires_at" datetime, "metadata" text, "created_at" datetime, "updated_at" datetime, foreign key("podcast_episode_id") references "podcast_episodes"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "networking_pairings" ("id" integer not null primary key autoincrement, "networking_session_id" integer not null, "participant_id" integer not null, "partner_id" integer, "round" integer not null, "group_key" varchar, "metadata" text, "created_at" datetime, "updated_at" datetime, foreign key("networking_session_id") references "networking_sessions"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "ad_groups" ("id" integer not null primary key autoincrement, "campaign_id" integer not null, "name" varchar not null, "daily_budget" numeric, "bid_amount" numeric, "status" varchar not null default 'active', "created_at" datetime, "updated_at" datetime, foreign key("campaign_id") references "campaigns"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "ai_sessions" ("id" integer not null primary key autoincrement, "user_id" integer not null, "tool" varchar not null, "status" varchar not null default 'pending', "prompt_tokens" integer not null default '0', "completion_tokens" integer not null default '0', "credit_cost" integer not null default '0', "input" text, "output" text, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id"));
CREATE TABLE IF NOT EXISTS "ai_byok_credentials" ("id" integer not null primary key autoincrement, "user_id" integer not null, "provider" varchar not null, "api_key" varchar not null, "meta" text, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id"));
CREATE TABLE IF NOT EXISTS "ai_subscription_plans" ("id" integer not null primary key autoincrement, "name" varchar not null, "slug" varchar not null, "limits" text, "price" numeric not null default '0', "created_at" datetime, "updated_at" datetime);
INSERT INTO ai_subscription_plans VALUES(1,'Basic','basic','{"daily":20000,"monthly":300000}',0,'2025-12-03 05:20:06','2025-12-03 05:20:06');
INSERT INTO ai_subscription_plans VALUES(2,'Pro','pro','{"daily":60000,"monthly":900000}',0,'2025-12-03 05:20:06','2025-12-03 05:20:06');
INSERT INTO ai_subscription_plans VALUES(3,'Enterprise','enterprise','{"daily":120000,"monthly":2000000}',0,'2025-12-03 05:20:06','2025-12-03 05:20:06');
CREATE TABLE IF NOT EXISTS "ai_user_subscriptions" ("id" integer not null primary key autoincrement, "user_id" integer not null, "ai_subscription_plan_id" integer not null, "renews_at" date, "status" varchar not null default 'active', "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id"), foreign key("ai_subscription_plan_id") references "ai_subscription_plans"("id"));
CREATE TABLE IF NOT EXISTS "ai_usage_aggregates" ("id" integer not null primary key autoincrement, "user_id" integer not null, "period_start" date not null, "period_end" date not null, "tokens_used" integer not null default '0', "sessions_count" integer not null default '0', "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id"));
CREATE TABLE IF NOT EXISTS "creatives" ("id" integer not null primary key autoincrement, "campaign_id" integer not null, "ad_group_id" integer, "type" varchar not null, "title" varchar not null, "body" text, "destination_url" varchar, "media_path" varchar, "status" varchar not null default 'draft', "cta" varchar, "created_at" datetime, "updated_at" datetime, foreign key("campaign_id") references "campaigns"("id") on delete cascade, foreign key("ad_group_id") references "ad_groups"("id") on delete set null);
CREATE TABLE IF NOT EXISTS "volunteering_opportunities" ("id" integer not null primary key autoincrement, "organisation_id" integer, "creator_id" integer not null, "title" varchar not null, "sector" varchar not null, "location" varchar, "commitment" varchar, "expenses_covered" tinyint(1) not null default '0', "verified" tinyint(1) not null default '0', "status" varchar not null default 'draft', "description" text, "created_at" datetime, "updated_at" datetime, foreign key("organisation_id") references "organizations"("id"), foreign key("creator_id") references "users"("id"));
CREATE TABLE IF NOT EXISTS "volunteering_applications" ("id" integer not null primary key autoincrement, "volunteering_opportunity_id" integer not null, "user_id" integer not null, "status" varchar not null default 'submitted', "motivation" text, "hours_contributed" integer not null default '0', "created_at" datetime, "updated_at" datetime, foreign key("volunteering_opportunity_id") references "volunteering_opportunities"("id"), foreign key("user_id") references "users"("id"));
CREATE TABLE IF NOT EXISTS "placements" ("id" integer not null primary key autoincrement, "name" varchar not null, "channel" varchar not null, "description" text, "is_active" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime);
INSERT INTO placements VALUES(1,'newsfeed','web','Feed hero placement',1,'2025-12-03 05:20:06','2025-12-03 05:20:06');
INSERT INTO placements VALUES(2,'sidebar','sidebar','Sidebar placement imported from Sngine baseline.',1,'2025-12-03 05:20:06','2025-12-03 05:20:06');
INSERT INTO placements VALUES(3,'profile','web','Profile rail placement',1,'2025-12-03 05:20:06','2025-12-03 05:20:06');
INSERT INTO placements VALUES(4,'search','web','Search result placement',1,'2025-12-03 05:20:06','2025-12-03 05:20:06');
INSERT INTO placements VALUES(5,'gigs','gigs','Gigs placement imported from Sngine baseline.',1,'2025-12-03 05:20:06','2025-12-03 05:20:06');
INSERT INTO placements VALUES(6,'jobs','web','Jobs listing rail placement',1,'2025-12-03 05:20:06','2025-12-03 05:20:06');
INSERT INTO placements VALUES(7,'projects','projects','Projects placement imported from Sngine baseline.',1,'2025-12-03 05:20:06','2025-12-03 05:20:06');
INSERT INTO placements VALUES(8,'podcasts','podcasts','Podcasts placement imported from Sngine baseline.',1,'2025-12-03 05:20:06','2025-12-03 05:20:06');
INSERT INTO placements VALUES(9,'webinars','webinars','Webinars placement imported from Sngine baseline.',1,'2025-12-03 05:20:06','2025-12-03 05:20:06');
INSERT INTO placements VALUES(10,'networking','networking','Networking placement imported from Sngine baseline.',1,'2025-12-03 05:20:06','2025-12-03 05:20:06');
INSERT INTO placements VALUES(11,'newsfeed_inline','web','Feed inline placement',1,'2025-12-03 05:20:06','2025-12-03 05:20:06');
INSERT INTO placements VALUES(12,'newsfeed_lane','web','Feed recommendation rail placement',1,'2025-12-03 05:20:06','2025-12-03 05:20:06');
INSERT INTO placements VALUES(13,'jobs_detail','web','Job detail CTA placement',1,'2025-12-03 05:20:06','2025-12-03 05:20:06');
INSERT INTO placements VALUES(14,'freelance','web','Freelance listings placement',1,'2025-12-03 05:20:06','2025-12-03 05:20:06');
INSERT INTO placements VALUES(15,'freelance_detail','web','Freelance detail placement',1,'2025-12-03 05:20:06','2025-12-03 05:20:06');
INSERT INTO placements VALUES(16,'freelance_dashboard','web','Freelance dashboard rail placement',1,'2025-12-03 05:20:06','2025-12-03 05:20:06');
INSERT INTO placements VALUES(17,'freelance_search','web','Freelance search result placement',1,'2025-12-03 05:20:06','2025-12-03 05:20:06');
INSERT INTO placements VALUES(18,'marketplace','web','Marketplace shelf placement',1,'2025-12-03 05:20:06','2025-12-03 05:20:06');
INSERT INTO placements VALUES(19,'marketplace_manager','web','Marketplace manager rail placement',1,'2025-12-03 05:20:06','2025-12-03 05:20:06');
INSERT INTO placements VALUES(20,'groups','web','Groups rail placement',1,'2025-12-03 05:20:06','2025-12-03 05:20:06');
INSERT INTO placements VALUES(21,'pages','web','Pages rail placement',1,'2025-12-03 05:20:06','2025-12-03 05:20:06');
INSERT INTO placements VALUES(22,'live_overlay','web','Live & events overlay placement',1,'2025-12-03 05:20:06','2025-12-03 05:20:06');
INSERT INTO placements VALUES(23,'story_interstitial','web','Stories interstitial placement',1,'2025-12-03 05:20:06','2025-12-03 05:20:06');
INSERT INTO placements VALUES(24,'video_swipe','mobile','Video swipe (mobile) placement',1,'2025-12-03 05:20:06','2025-12-03 05:20:06');
CREATE TABLE IF NOT EXISTS "targeting_rules" ("id" integer not null primary key autoincrement, "campaign_id" integer not null, "type" varchar not null, "value" varchar not null, "operator" varchar, "created_at" datetime, "updated_at" datetime, foreign key("campaign_id") references "campaigns"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "metrics" ("id" integer not null primary key autoincrement, "campaign_id" integer not null, "impressions" integer not null default '0', "clicks" integer not null default '0', "conversions" integer not null default '0', "spend" numeric not null default '0', "recorded_at" datetime not null, "created_at" datetime, "updated_at" datetime, foreign key("campaign_id") references "campaigns"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "forecasts" ("id" integer not null primary key autoincrement, "campaign_id" integer not null, "reach" integer not null default '0', "clicks" integer not null default '0', "conversions" integer not null default '0', "estimated_spend" numeric not null default '0', "assumptions" text, "created_at" datetime, "updated_at" datetime, foreign key("campaign_id") references "campaigns"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "keyword_prices" ("id" integer not null primary key autoincrement, "keyword" varchar not null, "cpc" numeric not null default '0', "cpa" numeric not null default '0', "cpm" numeric not null default '0', "created_at" datetime, "updated_at" datetime, "search_volume" integer not null default '0', "competition_score" numeric not null default '0', "quality_score" numeric not null default '0.5', "ctr" numeric not null default '0', "conversion_rate" numeric not null default '0', "placement_multiplier" numeric not null default '1', "currency" varchar not null default 'USD', "last_synced_at" datetime);
INSERT INTO keyword_prices VALUES(1,'networking',1.19999999999999995,6.5,3.29999999999999982,'2025-12-03 05:20:06','2025-12-03 05:20:06',0,0,0.5,0,0,1,'USD',NULL);
INSERT INTO keyword_prices VALUES(2,'jobs',1,7.5,3.89999999999999991,'2025-12-03 05:20:06','2025-12-03 05:20:06',0,0,0.5,0,0,1,'USD',NULL);
INSERT INTO keyword_prices VALUES(3,'freelance',0.900000000000000022,5.79999999999999982,3.10000000000000008,'2025-12-03 05:20:06','2025-12-03 05:20:06',0,0,0.5,0,0,1,'USD',NULL);
INSERT INTO keyword_prices VALUES(4,'podcast',0.800000000000000044,5.40000000000000035,2.89999999999999991,'2025-12-03 05:20:06','2025-12-03 05:20:06',0,0,0.5,0,0,1,'USD',NULL);
INSERT INTO keyword_prices VALUES(5,'webinar',1.10000000000000008,6.90000000000000035,3.60000000000000008,'2025-12-03 05:20:06','2025-12-03 05:20:06',0,0,0.5,0,0,1,'USD',NULL);
CREATE TABLE IF NOT EXISTS "affiliate_referrals" ("id" integer not null primary key autoincrement, "referrer_id" integer not null, "referred_user_id" integer not null, "campaign_id" integer, "commission" numeric not null default '0', "status" varchar not null default 'pending', "converted_at" datetime, "created_at" datetime, "updated_at" datetime, foreign key("referrer_id") references "users"("id") on delete cascade, foreign key("referred_user_id") references "users"("id") on delete cascade, foreign key("campaign_id") references "campaigns"("id") on delete set null);
CREATE TABLE IF NOT EXISTS "affiliate_payouts" ("id" integer not null primary key autoincrement, "affiliate_id" integer not null, "amount" numeric not null, "status" varchar not null default 'requested', "requested_at" datetime, "processed_at" datetime, "notes" text, "created_at" datetime, "updated_at" datetime, foreign key("affiliate_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "notifications" ("id" varchar not null, "type" varchar not null, "notifiable_type" varchar not null, "notifiable_id" integer not null, "data" text not null, "read_at" datetime, "created_at" datetime, "updated_at" datetime, "resource_type" varchar, "resource_id" varchar, "title" varchar, "message" text, "action_url" varchar, primary key ("id"));
CREATE TABLE IF NOT EXISTS "utilities_calendar_events" ("id" integer not null primary key autoincrement, "user_id" integer not null, "source" varchar not null, "source_id" varchar not null, "title" varchar not null, "subtitle" varchar, "description" text, "starts_at" datetime not null, "ends_at" datetime, "location" varchar, "status" varchar not null default 'scheduled', "metadata" text, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "live_streaming_engagements" ("id" integer not null primary key autoincrement, "live_streaming_id" integer not null, "user_id" integer, "type" varchar not null, "amount" numeric not null default '0', "payload" text, "created_at" datetime, "updated_at" datetime, foreign key("live_streaming_id") references "live_streamings"("streaming_id") on delete cascade, foreign key("user_id") references "users"("id") on delete set null);
CREATE TABLE IF NOT EXISTS "audit_logs" ("id" integer not null primary key autoincrement, "actor_id" integer, "target_type" varchar, "target_id" integer, "action" varchar not null, "changes" text, "source" varchar not null default 'web', "created_at" datetime, "updated_at" datetime);
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('migrations',65);
INSERT INTO sqlite_sequence VALUES('users',1);
INSERT INTO sqlite_sequence VALUES('placements',24);
INSERT INTO sqlite_sequence VALUES('keyword_prices',5);
INSERT INTO sqlite_sequence VALUES('ats_pipelines',1);
INSERT INTO sqlite_sequence VALUES('ats_stages',5);
INSERT INTO sqlite_sequence VALUES('jobs_categories',4);
INSERT INTO sqlite_sequence VALUES('webinars',3);
INSERT INTO sqlite_sequence VALUES('networking_sessions',2);
INSERT INTO sqlite_sequence VALUES('podcast_series',2);
INSERT INTO sqlite_sequence VALUES('interviews',2);
INSERT INTO sqlite_sequence VALUES('ai_subscription_plans',3);
CREATE UNIQUE INDEX "users_email_unique" on "users" ("email");
CREATE INDEX "personal_access_tokens_tokenable_type_tokenable_id_index" on "personal_access_tokens" ("tokenable_type", "tokenable_id");
CREATE UNIQUE INDEX "personal_access_tokens_token_unique" on "personal_access_tokens" ("token");
CREATE INDEX "projects_author_id_index" on "projects" ("author_id");
CREATE INDEX "projects_project_category_index" on "projects" ("project_category");
CREATE INDEX "projects_slug_index" on "projects" ("slug");
CREATE INDEX "projects_project_type_index" on "projects" ("project_type");
CREATE INDEX "projects_project_payout_type_index" on "projects" ("project_payout_type");
CREATE INDEX "projects_project_min_price_index" on "projects" ("project_min_price");
CREATE INDEX "projects_project_max_price_index" on "projects" ("project_max_price");
CREATE INDEX "projects_project_duration_index" on "projects" ("project_duration");
CREATE INDEX "projects_project_expert_level_index" on "projects" ("project_expert_level");
CREATE INDEX "projects_project_location_index" on "projects" ("project_location");
CREATE INDEX "projects_is_featured_index" on "projects" ("is_featured");
CREATE INDEX "projects_status_index" on "projects" ("status");
CREATE INDEX "projects_project_title_index" on "projects" ("project_title");
CREATE INDEX "gig_orders_author_id_index" on "gig_orders" ("author_id");
CREATE INDEX "gig_orders_gig_id_index" on "gig_orders" ("gig_id");
CREATE INDEX "gig_orders_status_index" on "gig_orders" ("status");
CREATE INDEX "project_durations_status_index" on "project_durations" ("status");
CREATE INDEX "project_durations_name_index" on "project_durations" ("name");
CREATE INDEX "seller_project_invites_seller_id_index" on "seller_project_invites" ("seller_id");
CREATE INDEX "seller_project_invites_project_id_index" on "seller_project_invites" ("project_id");
CREATE INDEX "project_locations_status_index" on "project_locations" ("status");
CREATE INDEX "project_locations_name_index" on "project_locations" ("name");
CREATE INDEX "escrow_disburse_methods_seller_id_index" on "escrow_disburse_methods" ("seller_id");
CREATE INDEX "escrow_disburse_methods_project_id_index" on "escrow_disburse_methods" ("project_id");
CREATE INDEX "escrow_disburse_methods_disburse_methods_id_index" on "escrow_disburse_methods" ("disburse_methods_id");
CREATE INDEX "gig_order_activities_sender_id_index" on "gig_order_activities" ("sender_id");
CREATE INDEX "gig_order_activities_receiver_id_index" on "gig_order_activities" ("receiver_id");
CREATE INDEX "gig_order_activities_gig_id_index" on "gig_order_activities" ("gig_id");
CREATE INDEX "gig_order_activities_order_id_index" on "gig_order_activities" ("order_id");
CREATE INDEX "gig_order_activities_type_index" on "gig_order_activities" ("type");
CREATE INDEX "project_activities_sender_id_index" on "project_activities" ("sender_id");
CREATE INDEX "project_activities_receiver_id_index" on "project_activities" ("receiver_id");
CREATE INDEX "project_activities_project_id_index" on "project_activities" ("project_id");
CREATE INDEX "disputes_created_by_index" on "disputes" ("created_by");
CREATE INDEX "disputes_created_to_index" on "disputes" ("created_to");
CREATE INDEX "disputes_proposal_id_index" on "disputes" ("proposal_id");
CREATE INDEX "disputes_gig_order_id_index" on "disputes" ("gig_order_id");
CREATE INDEX "disputes_status_index" on "disputes" ("status");
CREATE INDEX "dispute_conversations_sender_id_index" on "dispute_conversations" ("sender_id");
CREATE INDEX "dispute_conversations_dispute_id_index" on "dispute_conversations" ("dispute_id");
CREATE INDEX "dispute_conversations_message_id_index" on "dispute_conversations" ("message_id");
CREATE INDEX "project_categories_parent_id_index" on "project_categories" ("parent_id");
CREATE INDEX "project_categories_slug_index" on "project_categories" ("slug");
CREATE INDEX "project_categories_status_index" on "project_categories" ("status");
CREATE INDEX "project_categories_name_index" on "project_categories" ("name");
CREATE INDEX "gig_categories_parent_id_index" on "gig_categories" ("parent_id");
CREATE INDEX "gig_categories_slug_index" on "gig_categories" ("slug");
CREATE INDEX "gig_categories_status_index" on "gig_categories" ("status");
CREATE INDEX "gig_categories_name_index" on "gig_categories" ("name");
CREATE INDEX "gig_category_features_category_id_index" on "gig_category_features" ("category_id");
CREATE INDEX "gig_category_features_label_index" on "gig_category_features" ("label");
CREATE INDEX "gigs_author_id_index" on "gigs" ("author_id");
CREATE INDEX "gigs_slug_index" on "gigs" ("slug");
CREATE INDEX "gigs_is_featured_index" on "gigs" ("is_featured");
CREATE INDEX "gigs_status_index" on "gigs" ("status");
CREATE INDEX "gigs_title_index" on "gigs" ("title");
CREATE INDEX "gigs_country_index" on "gigs" ("country");
CREATE INDEX "gig_plans_gig_id_index" on "gig_plans" ("gig_id");
CREATE INDEX "gig_plans_title_index" on "gig_plans" ("title");
CREATE INDEX "gig_addons_gig_id_index" on "gig_addons" ("gig_id");
CREATE INDEX "gig_addons_addon_id_index" on "gig_addons" ("addon_id");
CREATE INDEX "gig_faqs_gig_id_index" on "gig_faqs" ("gig_id");
CREATE INDEX "gig_tags_gig_id_index" on "gig_tags" ("gig_id");
CREATE INDEX "gig_tags_tag_name_index" on "gig_tags" ("tag_name");
CREATE INDEX "gig_category_link_gig_id_index" on "gig_category_link" ("gig_id");
CREATE INDEX "gig_category_link_category_id_index" on "gig_category_link" ("category_id");
CREATE INDEX "gig_category_link_category_level_index" on "gig_category_link" ("category_level");
CREATE INDEX "advertisers_status_index" on "advertisers" ("status");
CREATE UNIQUE INDEX "freelance_tags_slug_unique" on "freelance_tags" ("slug");
CREATE INDEX "headhunter_profiles_user_id_status_index" on "headhunter_profiles" ("user_id", "status");
CREATE INDEX "headhunter_profiles_status_index" on "headhunter_profiles" ("status");
CREATE INDEX "headhunter_mandates_organisation_id_status_index" on "headhunter_mandates" ("organisation_id", "status");
CREATE INDEX "headhunter_mandates_status_index" on "headhunter_mandates" ("status");
CREATE INDEX "headhunter_candidates_user_id_index" on "headhunter_candidates" ("user_id");
CREATE UNIQUE INDEX "headhunter_pipeline_items_headhunter_mandate_id_headhunter_candidate_id_unique" on "headhunter_pipeline_items" ("headhunter_mandate_id", "headhunter_candidate_id");
CREATE INDEX "headhunter_pipeline_items_stage_index" on "headhunter_pipeline_items" ("stage");
CREATE INDEX "headhunter_interviews_scheduled_at_index" on "headhunter_interviews" ("scheduled_at");
CREATE INDEX "headhunter_interviews_status_index" on "headhunter_interviews" ("status");
CREATE UNIQUE INDEX "company_profiles_slug_unique" on "company_profiles" ("slug");
CREATE UNIQUE INDEX "jobs_slug_unique" on "jobs" ("slug");
CREATE UNIQUE INDEX "jobs_categories_slug_unique" on "jobs_categories" ("slug");
CREATE UNIQUE INDEX "pro_network_connection_caches_user_id_connection_id_unique" on "pro_network_connection_caches" ("user_id", "connection_id");
CREATE UNIQUE INDEX "pro_network_mutual_connections_user_id_target_user_id_unique" on "pro_network_mutual_connections" ("user_id", "target_user_id");
CREATE UNIQUE INDEX "pro_network_professional_profiles_public_url_unique" on "pro_network_professional_profiles" ("public_url");
CREATE UNIQUE INDEX "pro_network_profile_skills_user_id_name_unique" on "pro_network_profile_skills" ("user_id", "name");
CREATE UNIQUE INDEX "pro_network_profile_interests_user_id_interest_unique" on "pro_network_profile_interests" ("user_id", "interest");
CREATE UNIQUE INDEX "pro_network_company_employees_company_profile_id_user_id_unique" on "pro_network_company_employees" ("company_profile_id", "user_id");
CREATE UNIQUE INDEX "pro_network_live_session_participants_live_session_id_user_id_unique" on "pro_network_live_session_participants" ("live_session_id", "user_id");
CREATE INDEX "pro_network_reactions_reactable_type_reactable_id_index" on "pro_network_reactions" ("reactable_type", "reactable_id");
CREATE UNIQUE INDEX "pro_network_reactions_reactable_id_reactable_type_user_id_unique" on "pro_network_reactions" ("reactable_id", "reactable_type", "user_id");
CREATE INDEX "pro_network_reaction_aggregates_reactable_type_reactable_id_index" on "pro_network_reaction_aggregates" ("reactable_type", "reactable_id");
CREATE UNIQUE INDEX "pro_network_hashtags_tag_unique" on "pro_network_hashtags" ("tag");
CREATE UNIQUE INDEX "pro_network_hashtags_normalized_unique" on "pro_network_hashtags" ("normalized");
CREATE INDEX "pro_network_hashtaggables_hashtaggable_type_hashtaggable_id_index" on "pro_network_hashtaggables" ("hashtaggable_type", "hashtaggable_id");
CREATE UNIQUE INDEX "hashtaggable_unique" on "pro_network_hashtaggables" ("hashtag_id", "hashtaggable_id", "hashtaggable_type");
CREATE UNIQUE INDEX "pro_network_story_metadata_story_id_unique" on "pro_network_story_metadata" ("story_id");
CREATE INDEX "pro_network_moderation_queue_moderatable_type_moderatable_id_index" on "pro_network_moderation_queue" ("moderatable_type", "moderatable_id");
CREATE UNIQUE INDEX "pro_network_bad_words_phrase_unique" on "pro_network_bad_words" ("phrase");
CREATE UNIQUE INDEX "analytics_metric_unique" on "pro_network_analytics_metrics" ("entity_type", "entity_id", "metric");
CREATE UNIQUE INDEX "pro_network_account_types_slug_unique" on "pro_network_account_types" ("slug");
CREATE UNIQUE INDEX "pro_network_user_account_types_user_id_account_type_id_unique" on "pro_network_user_account_types" ("user_id", "account_type_id");
CREATE UNIQUE INDEX "pro_network_user_feature_flags_user_id_feature_unique" on "pro_network_user_feature_flags" ("user_id", "feature");
CREATE UNIQUE INDEX "pro_network_newsletter_subscriptions_email_unique" on "pro_network_newsletter_subscriptions" ("email");
CREATE UNIQUE INDEX "pro_network_post_enhancements_post_id_unique" on "pro_network_post_enhancements" ("post_id");
CREATE INDEX "recordings_recordable_type_recordable_id_index" on "recordings" ("recordable_type", "recordable_id");
CREATE INDEX "campaigns_advertiser_id_start_date_index" on "campaigns" ("advertiser_id", "start_date");
CREATE INDEX "campaigns_advertiser_id_status_index" on "campaigns" ("advertiser_id", "status");
CREATE INDEX "campaigns_status_index" on "campaigns" ("status");
CREATE INDEX "campaigns_placement_index" on "campaigns" ("placement");
CREATE INDEX "campaigns_approval_state_index" on "campaigns" ("approval_state");
CREATE INDEX "launchpad_programmes_creator_id_status_index" on "launchpad_programmes" ("creator_id", "status");
CREATE INDEX "launchpad_programmes_status_index" on "launchpad_programmes" ("status");
CREATE INDEX "launchpad_tasks_launchpad_programme_id_order_index" on "launchpad_tasks" ("launchpad_programme_id", "order");
CREATE INDEX "launchpad_applications_user_id_status_index" on "launchpad_applications" ("user_id", "status");
CREATE INDEX "launchpad_applications_status_index" on "launchpad_applications" ("status");
CREATE INDEX "launchpad_interviews_status_index" on "launchpad_interviews" ("status");
CREATE INDEX "tickets_ticketable_type_ticketable_id_index" on "tickets" ("ticketable_type", "ticketable_id");
CREATE UNIQUE INDEX "launchpad_application_task_progress_launchpad_application_id_launchpad_task_id_unique" on "launchpad_application_task_progress" ("launchpad_application_id", "launchpad_task_id");
CREATE UNIQUE INDEX "networking_contact_exchanges_networking_session_id_user_id_partner_id_unique" on "networking_contact_exchanges" ("networking_session_id", "user_id", "partner_id");
CREATE INDEX "networking_contact_exchanges_networking_session_id_user_id_index" on "networking_contact_exchanges" ("networking_session_id", "user_id");
CREATE UNIQUE INDEX "podcast_series_followers_podcast_series_id_user_id_unique" on "podcast_series_followers" ("podcast_series_id", "user_id");
CREATE UNIQUE INDEX "podcast_episode_entitlements_podcast_episode_id_user_id_entitlement_type_unique" on "podcast_episode_entitlements" ("podcast_episode_id", "user_id", "entitlement_type");
CREATE UNIQUE INDEX "networking_pairings_participant_round_unique" on "networking_pairings" ("networking_session_id", "participant_id", "round");
CREATE INDEX "networking_pairings_networking_session_id_round_index" on "networking_pairings" ("networking_session_id", "round");
CREATE INDEX "networking_pairings_networking_session_id_partner_id_index" on "networking_pairings" ("networking_session_id", "partner_id");
CREATE INDEX "ad_groups_status_index" on "ad_groups" ("status");
CREATE INDEX "ai_sessions_user_id_tool_index" on "ai_sessions" ("user_id", "tool");
CREATE INDEX "ai_sessions_status_index" on "ai_sessions" ("status");
CREATE UNIQUE INDEX "ai_byok_credentials_user_id_provider_unique" on "ai_byok_credentials" ("user_id", "provider");
CREATE UNIQUE INDEX "ai_subscription_plans_slug_unique" on "ai_subscription_plans" ("slug");
CREATE UNIQUE INDEX "ai_user_subscriptions_user_id_ai_subscription_plan_id_unique" on "ai_user_subscriptions" ("user_id", "ai_subscription_plan_id");
CREATE INDEX "ai_user_subscriptions_status_index" on "ai_user_subscriptions" ("status");
CREATE INDEX "ai_usage_aggregates_user_id_period_start_period_end_index" on "ai_usage_aggregates" ("user_id", "period_start", "period_end");
CREATE INDEX "creatives_type_index" on "creatives" ("type");
CREATE INDEX "creatives_status_index" on "creatives" ("status");
CREATE INDEX "volunteering_opportunities_creator_id_status_index" on "volunteering_opportunities" ("creator_id", "status");
CREATE INDEX "volunteering_opportunities_organisation_id_index" on "volunteering_opportunities" ("organisation_id");
CREATE INDEX "volunteering_opportunities_status_index" on "volunteering_opportunities" ("status");
CREATE INDEX "volunteering_applications_user_id_status_index" on "volunteering_applications" ("user_id", "status");
CREATE INDEX "volunteering_applications_status_index" on "volunteering_applications" ("status");
CREATE UNIQUE INDEX "placements_name_unique" on "placements" ("name");
CREATE INDEX "placements_channel_index" on "placements" ("channel");
CREATE INDEX "placements_is_active_index" on "placements" ("is_active");
CREATE INDEX "targeting_rules_campaign_id_type_index" on "targeting_rules" ("campaign_id", "type");
CREATE INDEX "targeting_rules_type_index" on "targeting_rules" ("type");
CREATE INDEX "metrics_campaign_id_recorded_at_index" on "metrics" ("campaign_id", "recorded_at");
CREATE INDEX "forecasts_campaign_id_index" on "forecasts" ("campaign_id");
CREATE UNIQUE INDEX "keyword_prices_keyword_unique" on "keyword_prices" ("keyword");
CREATE UNIQUE INDEX "affiliate_referrals_referred_user_id_campaign_id_unique" on "affiliate_referrals" ("referred_user_id", "campaign_id");
CREATE INDEX "affiliate_referrals_status_index" on "affiliate_referrals" ("status");
CREATE INDEX "affiliate_referrals_converted_at_index" on "affiliate_referrals" ("converted_at");
CREATE INDEX "affiliate_payouts_status_index" on "affiliate_payouts" ("status");
CREATE INDEX "affiliate_payouts_requested_at_index" on "affiliate_payouts" ("requested_at");
CREATE INDEX "affiliate_payouts_processed_at_index" on "affiliate_payouts" ("processed_at");
CREATE INDEX "notifications_notifiable_type_notifiable_id_index" on "notifications" ("notifiable_type", "notifiable_id");
CREATE UNIQUE INDEX "utilities_calendar_events_user_source_unique" on "utilities_calendar_events" ("user_id", "source", "source_id");
CREATE INDEX "utilities_calendar_events_source_index" on "utilities_calendar_events" ("source");
CREATE INDEX "utilities_calendar_events_starts_at_index" on "utilities_calendar_events" ("starts_at");
CREATE INDEX "utilities_calendar_events_status_index" on "utilities_calendar_events" ("status");
CREATE INDEX "notifications_resource_type_index" on "notifications" ("resource_type");
CREATE INDEX "live_streaming_engagements_live_streaming_id_type_index" on "live_streaming_engagements" ("live_streaming_id", "type");
CREATE INDEX "audit_logs_actor_id_index" on "audit_logs" ("actor_id");
CREATE INDEX "jobs_company_id_index" on "jobs" ("company_id");
CREATE INDEX "jobs_status_index" on "jobs" ("status");
CREATE INDEX "jobs_status_published_at_index" on "jobs" ("status", "published_at");
CREATE INDEX "job_applications_job_id_index" on "job_applications" ("job_id");
CREATE INDEX "job_applications_candidate_id_index" on "job_applications" ("candidate_id");
CREATE INDEX "job_applications_status_index" on "job_applications" ("status");
CREATE UNIQUE INDEX "job_bookmarks_job_user_unique" on "job_bookmarks" ("job_id", "user_id");
CREATE INDEX "webinars_host_id_index" on "webinars" ("host_id");
CREATE INDEX "webinars_starts_at_index" on "webinars" ("starts_at");
CREATE INDEX "webinars_status_index" on "webinars" ("status");
CREATE INDEX "networking_sessions_host_id_index" on "networking_sessions" ("host_id");
CREATE INDEX "networking_sessions_starts_at_index" on "networking_sessions" ("starts_at");
CREATE INDEX "podcast_series_host_id_index" on "podcast_series" ("host_id");
CREATE INDEX "podcast_series_is_public_index" on "podcast_series" ("is_public");
CREATE INDEX "interviews_host_id_index" on "interviews" ("host_id");
CREATE INDEX "interviews_scheduled_at_index" on "interviews" ("scheduled_at");
CREATE INDEX "audit_logs_target_index" on "audit_logs" ("target_type", "target_id");
CREATE INDEX "advertisers_user_id_status_index" on "advertisers" ("user_id", "status");
CREATE INDEX "ad_groups_campaign_id_status_index" on "ad_groups" ("campaign_id", "status");
COMMIT;
