<?php

$packageConfigPath = base_path('Gigvora-Addons/Advertisement-Addon/Advertisement_Laravel_package/config/advertisement.php');

$packageDefaults = file_exists($packageConfigPath)
    ? require $packageConfigPath
    : [
        'enabled' => env('ADS_ENABLED', true),
        'allow_author_view' => env('ADS_AUTHOR_VIEW_ENABLED', false),
        'approval_required' => env('ADS_APPROVAL_ENABLED', true),
        'default_budget' => env('ADS_DEFAULT_BUDGET', 50.00),
        'minimum_budget' => env('ADS_MINIMUM_BUDGET', 5.00),
        'bidding' => [
            'click_cost' => env('ADS_COST_CLICK', 0.65),
            'view_cost' => env('ADS_COST_VIEW', 8.00),
            'conversion_cost' => env('ADS_COST_CONVERSION', 9.25),
        ],
        'placements' => [],
        'features' => [
            'forecasting' => env('ADS_FORECAST_ENABLED', true),
            'simulation' => env('ADS_SIMULATION_ENABLED', true),
            'keyword_pricing' => env('ADS_KEYWORD_PRICING_ENABLED', true),
            'affiliate' => env('ADS_AFFILIATE_ENABLED', true),
        ],
        'roles' => [
            'administrator' => ['approve_campaigns', 'manage_placements', 'view_all_reports'],
            'advertiser' => ['create_campaigns', 'manage_creatives', 'view_own_reports'],
            'analyst' => ['view_all_reports'],
        ],
        'limits' => [
            'daily_spend' => env('ADS_DAILY_SPEND_LIMIT', 500),
            'lifetime_spend' => env('ADS_LIFETIME_SPEND_LIMIT', 5000),
        ],
        'affiliate' => [
            'enabled' => env('AFFILIATE_ENABLED', true),
            'commission_rate' => env('AFFILIATE_COMMISSION_RATE', 0.1),
            'payout_threshold' => env('AFFILIATE_PAYOUT_THRESHOLD', 50),
            'cooldown_days' => env('AFFILIATE_PAYOUT_COOLDOWN', 7),
        ],
    ];

return array_replace_recursive($packageDefaults, [
    'routes' => [
        'web_prefix' => 'addons/advertisement',
        'api_prefix' => 'api/advertisement',
        'name_prefix' => 'advertisement.',
        'api_name_prefix' => 'api.advertisement.',
    ],
    'placements' => [
        'newsfeed' => [
            'label' => 'Feed hero',
            'component' => 'advertisement::components.ad_feed_card',
            'creative_types' => ['banner', 'video', 'text'],
            'channel' => 'web',
            'frequency_cap' => ['per_session' => 1, 'per_100_cards' => 1],
            'weights' => ['ctr' => 0.35, 'conversion' => 0.2, 'pacing' => 0.2, 'freshness' => 0.15, 'diversity' => 0.1],
            'pricing_multiplier' => 1.15,
        ],
        'newsfeed_inline' => [
            'label' => 'Feed inline',
            'component' => 'advertisement::components.ad_feed_card',
            'creative_types' => ['text', 'banner'],
            'channel' => 'web',
            'frequency_cap' => ['per_25_cards' => 1],
            'weights' => ['ctr' => 0.3, 'conversion' => 0.2, 'pacing' => 0.25, 'freshness' => 0.15, 'diversity' => 0.1],
            'pricing_multiplier' => 1.05,
        ],
        'newsfeed_lane' => [
            'label' => 'Feed recommendation rail',
            'component' => 'advertisement::components.ad_feed_card',
            'creative_types' => ['banner', 'recommendation'],
            'channel' => 'web',
            'frequency_cap' => ['per_lane' => 1],
            'weights' => ['ctr' => 0.25, 'conversion' => 0.15, 'pacing' => 0.25, 'freshness' => 0.2, 'diversity' => 0.15],
            'pricing_multiplier' => 1.0,
        ],
        'profile' => [
            'label' => 'Profile rail',
            'component' => 'advertisement::components.ad_banner',
            'creative_types' => ['banner', 'text'],
            'channel' => 'web',
            'frequency_cap' => ['per_profile' => 1],
            'weights' => ['ctr' => 0.25, 'conversion' => 0.25, 'pacing' => 0.2, 'freshness' => 0.2, 'diversity' => 0.1],
            'pricing_multiplier' => 1.05,
        ],
        'search' => [
            'label' => 'Search result',
            'component' => 'advertisement::components.ad_search_result',
            'creative_types' => ['search', 'text'],
            'channel' => 'web',
            'frequency_cap' => ['per_page' => 2],
            'weights' => ['ctr' => 0.4, 'conversion' => 0.25, 'pacing' => 0.15, 'freshness' => 0.1, 'diversity' => 0.1],
            'pricing_multiplier' => 1.25,
        ],
        'jobs' => [
            'label' => 'Jobs listing rail',
            'component' => 'advertisement::components.ad_banner',
            'creative_types' => ['banner', 'text'],
            'channel' => 'web',
            'frequency_cap' => ['per_page' => 1],
            'weights' => ['ctr' => 0.28, 'conversion' => 0.27, 'pacing' => 0.2, 'freshness' => 0.15, 'diversity' => 0.1],
            'pricing_multiplier' => 1.1,
        ],
        'jobs_detail' => [
            'label' => 'Job detail CTA',
            'component' => 'advertisement::components.ad_banner',
            'creative_types' => ['banner', 'text'],
            'channel' => 'web',
            'frequency_cap' => ['per_detail' => 1],
            'weights' => ['ctr' => 0.32, 'conversion' => 0.3, 'pacing' => 0.18, 'freshness' => 0.1, 'diversity' => 0.1],
            'pricing_multiplier' => 1.2,
        ],
        'freelance' => [
            'label' => 'Freelance listings',
            'component' => 'advertisement::components.ad_banner',
            'creative_types' => ['banner', 'text'],
            'channel' => 'web',
            'frequency_cap' => ['per_page' => 1],
            'weights' => ['ctr' => 0.3, 'conversion' => 0.25, 'pacing' => 0.2, 'freshness' => 0.15, 'diversity' => 0.1],
            'pricing_multiplier' => 1.08,
        ],
        'freelance_detail' => [
            'label' => 'Freelance detail',
            'component' => 'advertisement::components.ad_banner',
            'creative_types' => ['banner', 'text'],
            'channel' => 'web',
            'frequency_cap' => ['per_detail' => 1],
            'weights' => ['ctr' => 0.33, 'conversion' => 0.28, 'pacing' => 0.19, 'freshness' => 0.1, 'diversity' => 0.1],
            'pricing_multiplier' => 1.18,
        ],
        'freelance_dashboard' => [
            'label' => 'Freelance dashboard rail',
            'component' => 'advertisement::components.ad_banner',
            'creative_types' => ['banner', 'text'],
            'channel' => 'web',
            'frequency_cap' => ['per_session' => 1],
            'weights' => ['ctr' => 0.26, 'conversion' => 0.24, 'pacing' => 0.2, 'freshness' => 0.2, 'diversity' => 0.1],
            'pricing_multiplier' => 1.12,
        ],
        'freelance_search' => [
            'label' => 'Freelance search result',
            'component' => 'advertisement::components.ad_search_result',
            'creative_types' => ['search', 'text'],
            'channel' => 'web',
            'frequency_cap' => ['per_page' => 1],
            'weights' => ['ctr' => 0.34, 'conversion' => 0.25, 'pacing' => 0.18, 'freshness' => 0.13, 'diversity' => 0.1],
            'pricing_multiplier' => 1.2,
        ],
        'marketplace' => [
            'label' => 'Marketplace shelf',
            'component' => 'advertisement::components.ad_banner',
            'creative_types' => ['banner', 'text'],
            'channel' => 'web',
            'frequency_cap' => ['per_page' => 1],
            'weights' => ['ctr' => 0.22, 'conversion' => 0.25, 'pacing' => 0.25, 'freshness' => 0.18, 'diversity' => 0.1],
            'pricing_multiplier' => 0.95,
        ],
        'marketplace_manager' => [
            'label' => 'Marketplace manager rail',
            'component' => 'advertisement::components.ad_banner',
            'creative_types' => ['banner', 'text'],
            'channel' => 'web',
            'frequency_cap' => ['per_session' => 1],
            'weights' => ['ctr' => 0.2, 'conversion' => 0.3, 'pacing' => 0.25, 'freshness' => 0.15, 'diversity' => 0.1],
            'pricing_multiplier' => 0.9,
        ],
        'groups' => [
            'label' => 'Groups rail',
            'component' => 'advertisement::components.ad_banner',
            'creative_types' => ['banner', 'text'],
            'channel' => 'web',
            'frequency_cap' => ['per_page' => 1],
            'weights' => ['ctr' => 0.24, 'conversion' => 0.25, 'pacing' => 0.22, 'freshness' => 0.19, 'diversity' => 0.1],
            'pricing_multiplier' => 1.0,
        ],
        'pages' => [
            'label' => 'Pages rail',
            'component' => 'advertisement::components.ad_banner',
            'creative_types' => ['banner', 'text'],
            'channel' => 'web',
            'frequency_cap' => ['per_page' => 1],
            'weights' => ['ctr' => 0.24, 'conversion' => 0.25, 'pacing' => 0.24, 'freshness' => 0.17, 'diversity' => 0.1],
            'pricing_multiplier' => 1.02,
        ],
        'live_overlay' => [
            'label' => 'Live & events overlay',
            'component' => 'advertisement::components.ad_feed_card',
            'creative_types' => ['video', 'banner'],
            'channel' => 'web',
            'frequency_cap' => ['per_event' => 1],
            'weights' => ['ctr' => 0.28, 'conversion' => 0.22, 'pacing' => 0.2, 'freshness' => 0.2, 'diversity' => 0.1],
            'pricing_multiplier' => 1.3,
        ],
        'story_interstitial' => [
            'label' => 'Stories interstitial',
            'component' => 'advertisement::components.ad_feed_card',
            'creative_types' => ['video', 'banner'],
            'channel' => 'web',
            'frequency_cap' => ['per_story_stack' => 1],
            'weights' => ['ctr' => 0.3, 'conversion' => 0.18, 'pacing' => 0.2, 'freshness' => 0.22, 'diversity' => 0.1],
            'pricing_multiplier' => 1.35,
        ],
        'video_swipe' => [
            'label' => 'Video swipe (mobile)',
            'component' => 'advertisement::components.ad_feed_card',
            'creative_types' => ['video'],
            'channel' => 'mobile',
            'frequency_cap' => ['per_10_swipes' => 1],
            'weights' => ['ctr' => 0.32, 'conversion' => 0.18, 'pacing' => 0.18, 'freshness' => 0.22, 'diversity' => 0.1],
            'pricing_multiplier' => 1.4,
        ],
    ],
    'navigation' => [
        'menu_label' => 'Ads Manager',
        'campaigns_label' => 'Campaigns',
        'creatives_label' => 'Creatives',
        'reports_label' => 'Reports',
    ],
]);

