<?php

return [
    'primary' => [
        [
            'key' => 'home',
            'label' => 'Home',
            'route' => 'dashboard',
            'match' => 'dashboard',
            'icon' => 'home',
        ],
        [
            'key' => 'jobs',
            'label' => 'Jobs',
            'route' => 'jobs.index',
            'match' => 'jobs.*',
            'icon' => 'briefcase',
            'feature' => 'jobs.features.enabled',
        ],
        [
            'key' => 'freelance',
            'label' => 'Freelance',
            'route' => 'freelance.dashboard',
            'match' => 'freelance.*',
            'icon' => 'handshake',
            'feature' => 'freelance.enabled',
        ],
        [
            'key' => 'live',
            'label' => 'Live',
            'route' => 'wnip.webinars.index',
            'match' => 'wnip.*',
            'icon' => 'broadcast',
            'feature' => 'webinar_networking_interview_podcast.enabled',
        ],
        [
            'key' => 'groups',
            'label' => 'Groups',
            'route' => 'groups.index',
            'match' => 'groups.*',
            'icon' => 'users',
        ],
        [
            'key' => 'pages',
            'label' => 'Pages',
            'route' => 'pages.index',
            'match' => 'pages.*',
            'icon' => 'layers',
        ],
        [
            'key' => 'messages',
            'label' => 'Messages',
            'route' => 'messages.index',
            'match' => 'messages.*',
            'icon' => 'chat',
        ],
    ],
    'groups' => [
        [
            'key' => 'ads',
            'label' => 'Ads Manager',
            'icon' => 'megaphone',
            'feature' => 'advertisement.enabled',
            'permission' => 'manage_advertisement',
            'children' => [
                [
                    'label' => 'Ads Overview',
                    'route' => 'advertisement.dashboard',
                    'match' => 'advertisement.dashboard',
                ],
                [
                    'label' => 'Campaigns',
                    'route' => 'advertisement.campaigns.index',
                    'match' => 'advertisement.campaigns.*',
                ],
                [
                    'label' => 'Ads Reports',
                    'route' => 'advertisement.reports.index',
                    'match' => 'advertisement.reports.*',
                ],
            ],
        ],
        [
            'key' => 'talent_ai',
            'label' => 'Talent & AI',
            'icon' => 'sparkles',
            'feature' => 'gigvora_talent_ai.enabled',
            'children' => [
                [
                    'label' => 'Headhunters',
                    'route' => 'addons.talent_ai.headhunters.dashboard',
                    'match' => 'addons.talent_ai.headhunters.*',
                    'feature' => 'gigvora_talent_ai.modules.headhunters.enabled',
                ],
                [
                    'label' => 'Experience Launchpad',
                    'route' => 'addons.talent_ai.launchpad.programmes.index',
                    'match' => 'addons.talent_ai.launchpad.*',
                    'feature' => 'gigvora_talent_ai.modules.launchpad.enabled',
                ],
                [
                    'label' => 'AI Workspace',
                    'route' => 'addons.talent_ai.ai_workspace.index',
                    'match' => 'addons.talent_ai.ai_workspace.*',
                    'feature' => 'gigvora_talent_ai.modules.ai_workspace.enabled',
                ],
                [
                    'label' => 'Volunteering',
                    'route' => 'addons.talent_ai.volunteering.opportunities.index',
                    'match' => 'addons.talent_ai.volunteering.*',
                    'feature' => 'gigvora_talent_ai.modules.volunteering.enabled',
                ],
                [
                    'label' => 'Talent & AI Admin',
                    'route' => 'addons.talent_ai.admin.config',
                    'match' => 'addons.talent_ai.admin.*',
                    'permission' => 'manage_talent_ai',
                ],
            ],
        ],
        [
            'key' => 'live',
            'label' => 'Live & Events',
            'icon' => 'broadcast',
            'feature' => 'webinar_networking_interview_podcast.enabled',
            'children' => [
                [
                    'label' => 'Live Hub',
                    'route' => 'liveCenter.hub',
                    'match' => 'liveCenter.hub',
                ],
                [
                    'label' => 'Webinars',
                    'route' => 'wnip.webinars.index',
                    'match' => 'wnip.webinars.*',
                    'feature' => 'webinar_networking_interview_podcast.features.webinars',
                ],
                [
                    'label' => 'Networking',
                    'route' => 'wnip.networking.index',
                    'match' => 'wnip.networking.*',
                    'feature' => 'webinar_networking_interview_podcast.features.networking',
                ],
                [
                    'label' => 'Podcasts',
                    'route' => 'wnip.podcasts.index',
                    'match' => 'wnip.podcasts.*',
                    'feature' => 'webinar_networking_interview_podcast.features.podcasts',
                ],
                [
                    'label' => 'Interviews',
                    'route' => 'wnip.interviews.index',
                    'match' => 'wnip.interviews.*',
                    'feature' => 'webinar_networking_interview_podcast.features.interviews',
                ],
            ],
        ],
        [
            'key' => 'utilities',
            'label' => 'Utilities',
            'icon' => 'sparkles',
            'children' => [
                [
                    'label' => 'Utilities Hub',
                    'route' => 'utilities.hub',
                    'match' => 'utilities.hub',
                ],
                [
                    'label' => 'My Network',
                    'route' => 'utilities.network',
                    'match' => 'utilities.network',
                    'feature' => 'pro_network_utilities_security_analytics.features.connections_graph',
                ],
                [
                    'label' => 'Professional Profile',
                    'route' => 'utilities.professional',
                    'match' => 'utilities.professional',
                    'feature' => 'pro_network_utilities_security_analytics.features.profile_professional_upgrades',
                ],
                [
                    'label' => 'Company Upgrades',
                    'route' => 'utilities.company',
                    'match' => 'utilities.company',
                    'feature' => 'pro_network_utilities_security_analytics.features.profile_professional_upgrades',
                ],
                [
                    'label' => 'Stories Creator',
                    'route' => 'utilities.stories.create',
                    'match' => 'utilities.stories.create',
                    'feature' => 'pro_network_utilities_security_analytics.features.stories_wrapper',
                ],
                [
                    'label' => 'Post Poll',
                    'route' => 'utilities.posts.poll',
                    'match' => 'utilities.posts.poll',
                    'feature' => 'pro_network_utilities_security_analytics.features.post_enhancements',
                ],
                [
                    'label' => 'Thread Composer',
                    'route' => 'utilities.posts.thread',
                    'match' => 'utilities.posts.thread',
                    'feature' => 'pro_network_utilities_security_analytics.features.post_enhancements',
                ],
                [
                    'label' => 'Celebrate Post',
                    'route' => 'utilities.posts.celebrate',
                    'match' => 'utilities.posts.celebrate',
                    'feature' => 'pro_network_utilities_security_analytics.features.post_enhancements',
                ],
                [
                    'label' => 'Hashtag Explorer',
                    'route' => 'utilities.hashtags',
                    'match' => 'utilities.hashtags',
                    'feature' => 'pro_network_utilities_security_analytics.features.hashtags',
                ],
            ],
        ],
    ],
    'secondary' => [
        [
            'key' => 'notifications',
            'label' => 'Notifications',
            'route' => 'notifications.index',
            'match' => 'notifications.*',
            'icon' => 'bell',
            'feature' => 'utilities.notifications.enabled',
        ],
        [
            'key' => 'saved',
            'label' => 'Saved',
            'route' => 'saved.index',
            'match' => 'saved.*',
            'icon' => 'bookmark',
            'feature' => 'utilities.bookmarks.enabled',
        ],
        [
            'key' => 'calendar',
            'label' => 'Schedule',
            'route' => 'calendar.index',
            'match' => 'calendar.*',
            'icon' => 'calendar',
            'feature' => 'utilities.calendar.enabled',
        ],
    ],
    'admin' => [
        [
            'label' => 'Admin Dashboard',
            'route' => 'admin.dashboard',
            'match' => 'admin.*',
            'permission' => 'access_admin_panel',
        ],
        [
            'label' => 'System Settings',
            'route' => 'settings.system',
            'match' => 'settings.system',
            'permission' => 'manage_system_settings',
        ],
        [
            'label' => 'Utilities Analytics',
            'route' => 'utilities.analytics',
            'match' => 'utilities.analytics',
            'permission' => 'viewAnalytics',
            'feature' => 'pro_network_utilities_security_analytics.features.analytics_hub',
        ],
        [
            'label' => 'Utilities Security',
            'route' => 'utilities.security',
            'match' => 'utilities.security',
            'permission' => 'viewSecurity',
            'feature' => 'pro_network_utilities_security_analytics.features.security_hardening',
        ],
        [
            'label' => 'Utilities Moderation',
            'route' => 'utilities.moderation',
            'match' => 'utilities.moderation',
            'permission' => 'moderate',
            'feature' => 'pro_network_utilities_security_analytics.features.moderation_tools',
        ],
    ],
    'profile_tabs' => [
        [
            'key' => 'timeline',
            'label' => 'Timeline',
            'route' => 'profile',
            'match' => 'profile',
        ],
        [
            'key' => 'photos_reels',
            'label' => 'Photos & Reels',
            'route' => 'profile.photos',
            'match' => 'profile.photos',
        ],
        [
            'key' => 'videos',
            'label' => 'Videos',
            'route' => 'profile.videos',
            'match' => 'profile.videos',
        ],
        [
            'key' => 'saved',
            'label' => 'Saved',
            'route' => 'profile.savePostList',
            'match' => 'profile.savePostList',
        ],
        [
            'key' => 'checkins',
            'label' => 'Check-ins',
            'route' => 'profile.checkins_list',
            'match' => 'profile.checkins_list',
        ],
    ],
    'settings' => [
        [
            'key' => 'account',
            'label' => 'Account Settings',
            'route' => 'all_settings.view',
            'match' => 'all_settings.view',
        ],
        [
            'key' => 'privacy_notifications',
            'label' => 'Privacy & Notifications',
            'route' => 'notifications.index',
            'match' => 'notifications.*',
        ],
    ],
    'mobile' => [
        'tabs' => [
            [
                'key' => 'feed',
                'label' => 'Feed',
                'route' => 'dashboard',
                'match' => 'dashboard',
                'icon' => 'home',
            ],
            [
                'key' => 'jobs',
                'label' => 'Jobs',
                'route' => 'jobs.index',
                'match' => 'jobs.*',
                'icon' => 'briefcase',
                'feature' => 'jobs.features.enabled',
            ],
            [
                'key' => 'freelance',
                'label' => 'Freelance',
                'route' => 'freelance.dashboard',
                'match' => 'freelance.*',
                'icon' => 'handshake',
                'feature' => 'freelance.enabled',
            ],
            [
                'key' => 'live',
                'label' => 'Live',
                'route' => 'wnip.webinars.index',
                'match' => 'wnip.*',
                'icon' => 'broadcast',
                'feature' => 'webinar_networking_interview_podcast.enabled',
            ],
            [
                'key' => 'profile',
                'label' => 'Profile',
                'route' => 'profile',
                'match' => 'profile.*',
                'icon' => 'user-circle',
            ],
        ],
        'drawer' => [
            [
                'key' => 'communities',
                'label' => 'Communities',
                'children' => [
                    [
                        'key' => 'groups',
                        'label' => 'Groups',
                        'route' => 'groups.index',
                        'match' => 'groups.*',
                        'icon' => 'users',
                    ],
                    [
                        'key' => 'pages',
                        'label' => 'Pages',
                        'route' => 'pages.index',
                        'match' => 'pages.*',
                        'icon' => 'layers',
                    ],
                ],
            ],
            [
                'key' => 'workflows',
                'label' => 'Workflows',
                'children' => [
                    [
                        'key' => 'messages',
                        'label' => 'Messages',
                        'route' => 'messages.index',
                        'match' => 'messages.*',
                        'icon' => 'chat',
                    ],
                    [
                        'key' => 'calendar',
                        'label' => 'My Schedule',
                        'route' => 'calendar.index',
                        'match' => 'calendar.*',
                        'icon' => 'calendar',
                        'feature' => 'utilities.calendar.enabled',
                    ],
                ],
            ],
            [
                'key' => 'utilities',
                'label' => 'Utilities',
                'children' => [
                    [
                        'key' => 'utilities_hub',
                        'label' => 'Utilities Hub',
                        'route' => 'utilities.hub',
                        'match' => 'utilities.hub',
                        'icon' => 'sparkles',
                    ],
                    [
                        'key' => 'utilities_network',
                        'label' => 'My Network',
                        'route' => 'utilities.network',
                        'match' => 'utilities.network',
                        'icon' => 'users',
                        'feature' => 'pro_network_utilities_security_analytics.features.connections_graph',
                    ],
                    [
                        'key' => 'utilities_profile',
                        'label' => 'Professional Profile',
                        'route' => 'utilities.professional',
                        'match' => 'utilities.professional',
                        'icon' => 'sparkles',
                        'feature' => 'pro_network_utilities_security_analytics.features.profile_professional_upgrades',
                    ],
                    [
                        'key' => 'utilities_stories',
                        'label' => 'Stories Creator',
                        'route' => 'utilities.stories.create',
                        'match' => 'utilities.stories.create',
                        'icon' => 'broadcast',
                        'feature' => 'pro_network_utilities_security_analytics.features.stories_wrapper',
                    ],
                    [
                        'key' => 'saved',
                        'label' => 'Saved Items',
                        'route' => 'saved.index',
                        'match' => 'saved.*',
                        'icon' => 'bookmark',
                        'feature' => 'utilities.bookmarks.enabled',
                    ],
                    [
                        'key' => 'notifications',
                        'label' => 'Notifications',
                        'route' => 'notifications.index',
                        'match' => 'notifications.*',
                        'icon' => 'bell',
                        'feature' => 'utilities.notifications.enabled',
                    ],
                ],
            ],
            [
                'key' => 'admin_settings',
                'label' => 'Admin & Settings',
                'children' => [
                    [
                        'key' => 'settings',
                        'label' => 'Settings',
                        'route' => 'all_settings.view',
                        'match' => 'all_settings.view',
                        'icon' => 'settings',
                    ],
                    [
                        'key' => 'admin',
                        'label' => 'Admin',
                        'route' => 'admin.dashboard',
                        'match' => 'admin.*',
                        'icon' => 'shield',
                        'permission' => 'access_admin_panel',
                    ],
                ],
            ],
        ],
    ],
];

